// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/pb/zeek_runner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求体
type AnalyzeRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskID               string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`                              // 任务ID
	Uuid                 string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                                  // UUID
	OnlyNotice           bool                   `protobuf:"varint,3,opt,name=onlyNotice,proto3" json:"onlyNotice,omitempty"`                     // 是否只生成notice日志
	PcapID               string                 `protobuf:"bytes,4,opt,name=pcapID,proto3" json:"pcapID,omitempty"`                              // pcap文件ID
	PcapPath             string                 `protobuf:"bytes,5,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`                          // pcap文件路径
	ScriptID             string                 `protobuf:"bytes,6,opt,name=scriptID,proto3" json:"scriptID,omitempty"`                          // 脚本ID
	ScriptPath           string                 `protobuf:"bytes,7,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`                      // 脚本路径
	ExtractedFilePath    string                 `protobuf:"bytes,8,opt,name=extractedFilePath,proto3" json:"extractedFilePath,omitempty"`        // 提取文件存储路径
	ExtractedFileMinSize int32                  `protobuf:"varint,9,opt,name=extractedFileMinSize,proto3" json:"extractedFileMinSize,omitempty"` // 提取文件最小大小(KB)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AnalyzeRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AnalyzeRequest) GetOnlyNotice() bool {
	if x != nil {
		return x.OnlyNotice
	}
	return false
}

func (x *AnalyzeRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *AnalyzeRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AnalyzeRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *AnalyzeRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *AnalyzeRequest) GetExtractedFilePath() string {
	if x != nil {
		return x.ExtractedFilePath
	}
	return ""
}

func (x *AnalyzeRequest) GetExtractedFileMinSize() int32 {
	if x != nil {
		return x.ExtractedFileMinSize
	}
	return 0
}

// 响应体
type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	PcapPath      string                 `protobuf:"bytes,3,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`     // pcap文件路径
	ScriptPath    string                 `protobuf:"bytes,4,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"` // 脚本路径
	StartTime     string                 `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`   // 任务开始时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AnalyzeResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AnalyzeResponse) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AnalyzeResponse) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *AnalyzeResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

var File_api_pb_zeek_runner_proto protoreflect.FileDescriptor

const file_api_pb_zeek_runner_proto_rawDesc = "" +
	"\n" +
	"\x18api/pb/zeek_runner.proto\x12\vzeek_runner\"\xae\x02\n" +
	"\x0eAnalyzeRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"onlyNotice\x18\x03 \x01(\bR\n" +
	"onlyNotice\x12\x16\n" +
	"\x06pcapID\x18\x04 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x05 \x01(\tR\bpcapPath\x12\x1a\n" +
	"\bscriptID\x18\x06 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\a \x01(\tR\n" +
	"scriptPath\x12,\n" +
	"\x11extractedFilePath\x18\b \x01(\tR\x11extractedFilePath\x122\n" +
	"\x14extractedFileMinSize\x18\t \x01(\x05R\x14extractedFileMinSize\"\x97\x01\n" +
	"\x0fAnalyzeResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpcapPath\x18\x03 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x04 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime2]\n" +
	"\x13ZeekAnalysisService\x12F\n" +
	"\aAnalyze\x12\x1b.zeek_runner.AnalyzeRequest\x1a\x1c.zeek_runner.AnalyzeResponse\"\x00B\x14Z\x12zeek_runner/api/pbb\x06proto3"

var (
	file_api_pb_zeek_runner_proto_rawDescOnce sync.Once
	file_api_pb_zeek_runner_proto_rawDescData []byte
)

func file_api_pb_zeek_runner_proto_rawDescGZIP() []byte {
	file_api_pb_zeek_runner_proto_rawDescOnce.Do(func() {
		file_api_pb_zeek_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_zeek_runner_proto_rawDesc), len(file_api_pb_zeek_runner_proto_rawDesc)))
	})
	return file_api_pb_zeek_runner_proto_rawDescData
}

var file_api_pb_zeek_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_pb_zeek_runner_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: zeek_runner.AnalyzeRequest
	(*AnalyzeResponse)(nil), // 1: zeek_runner.AnalyzeResponse
}
var file_api_pb_zeek_runner_proto_depIdxs = []int32{
	0, // 0: zeek_runner.ZeekAnalysisService.Analyze:input_type -> zeek_runner.AnalyzeRequest
	1, // 1: zeek_runner.ZeekAnalysisService.Analyze:output_type -> zeek_runner.AnalyzeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pb_zeek_runner_proto_init() }
func file_api_pb_zeek_runner_proto_init() {
	if File_api_pb_zeek_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_zeek_runner_proto_rawDesc), len(file_api_pb_zeek_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_zeek_runner_proto_goTypes,
		DependencyIndexes: file_api_pb_zeek_runner_proto_depIdxs,
		MessageInfos:      file_api_pb_zeek_runner_proto_msgTypes,
	}.Build()
	File_api_pb_zeek_runner_proto = out.File
	file_api_pb_zeek_runner_proto_goTypes = nil
	file_api_pb_zeek_runner_proto_depIdxs = nil
}
