// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/pb/zeek_runner.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZeekAnalysisService_Analyze_FullMethodName             = "/zeek_runner.ZeekAnalysisService/Analyze"
	ZeekAnalysisService_AsyncAnalyze_FullMethodName        = "/zeek_runner.ZeekAnalysisService/AsyncAnalyze"
	ZeekAnalysisService_GetTaskStatus_FullMethodName       = "/zeek_runner.ZeekAnalysisService/GetTaskStatus"
	ZeekAnalysisService_GetParentTaskStatus_FullMethodName = "/zeek_runner.ZeekAnalysisService/GetParentTaskStatus"
	ZeekAnalysisService_HealthCheck_FullMethodName         = "/zeek_runner.ZeekAnalysisService/HealthCheck"
	ZeekAnalysisService_VersionCheck_FullMethodName        = "/zeek_runner.ZeekAnalysisService/VersionCheck"
	ZeekAnalysisService_ZeekSyntaxCheck_FullMethodName     = "/zeek_runner.ZeekAnalysisService/ZeekSyntaxCheck"
)

// ZeekAnalysisServiceClient is the client API for ZeekAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC服务定义
type ZeekAnalysisServiceClient interface {
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	AsyncAnalyze(ctx context.Context, in *AsyncAnalyzeRequest, opts ...grpc.CallOption) (*AsyncAnalyzeResponse, error)
	GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
	GetParentTaskStatus(ctx context.Context, in *ParentTaskStatusRequest, opts ...grpc.CallOption) (*ParentTaskStatusResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	VersionCheck(ctx context.Context, in *VersionCheckRequest, opts ...grpc.CallOption) (*VersionCheckResponse, error)
	ZeekSyntaxCheck(ctx context.Context, in *ZeekSyntaxCheckRequest, opts ...grpc.CallOption) (*ZeekSyntaxCheckResponse, error)
}

type zeekAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZeekAnalysisServiceClient(cc grpc.ClientConnInterface) ZeekAnalysisServiceClient {
	return &zeekAnalysisServiceClient{cc}
}

func (c *zeekAnalysisServiceClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, ZeekAnalysisService_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zeekAnalysisServiceClient) AsyncAnalyze(ctx context.Context, in *AsyncAnalyzeRequest, opts ...grpc.CallOption) (*AsyncAnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsyncAnalyzeResponse)
	err := c.cc.Invoke(ctx, ZeekAnalysisService_AsyncAnalyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zeekAnalysisServiceClient) GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, ZeekAnalysisService_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zeekAnalysisServiceClient) GetParentTaskStatus(ctx context.Context, in *ParentTaskStatusRequest, opts ...grpc.CallOption) (*ParentTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParentTaskStatusResponse)
	err := c.cc.Invoke(ctx, ZeekAnalysisService_GetParentTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zeekAnalysisServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ZeekAnalysisService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zeekAnalysisServiceClient) VersionCheck(ctx context.Context, in *VersionCheckRequest, opts ...grpc.CallOption) (*VersionCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionCheckResponse)
	err := c.cc.Invoke(ctx, ZeekAnalysisService_VersionCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zeekAnalysisServiceClient) ZeekSyntaxCheck(ctx context.Context, in *ZeekSyntaxCheckRequest, opts ...grpc.CallOption) (*ZeekSyntaxCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZeekSyntaxCheckResponse)
	err := c.cc.Invoke(ctx, ZeekAnalysisService_ZeekSyntaxCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZeekAnalysisServiceServer is the server API for ZeekAnalysisService service.
// All implementations must embed UnimplementedZeekAnalysisServiceServer
// for forward compatibility.
//
// gRPC服务定义
type ZeekAnalysisServiceServer interface {
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	AsyncAnalyze(context.Context, *AsyncAnalyzeRequest) (*AsyncAnalyzeResponse, error)
	GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error)
	GetParentTaskStatus(context.Context, *ParentTaskStatusRequest) (*ParentTaskStatusResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	VersionCheck(context.Context, *VersionCheckRequest) (*VersionCheckResponse, error)
	ZeekSyntaxCheck(context.Context, *ZeekSyntaxCheckRequest) (*ZeekSyntaxCheckResponse, error)
	mustEmbedUnimplementedZeekAnalysisServiceServer()
}

// UnimplementedZeekAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZeekAnalysisServiceServer struct{}

func (UnimplementedZeekAnalysisServiceServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedZeekAnalysisServiceServer) AsyncAnalyze(context.Context, *AsyncAnalyzeRequest) (*AsyncAnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AsyncAnalyze not implemented")
}
func (UnimplementedZeekAnalysisServiceServer) GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedZeekAnalysisServiceServer) GetParentTaskStatus(context.Context, *ParentTaskStatusRequest) (*ParentTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParentTaskStatus not implemented")
}
func (UnimplementedZeekAnalysisServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedZeekAnalysisServiceServer) VersionCheck(context.Context, *VersionCheckRequest) (*VersionCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VersionCheck not implemented")
}
func (UnimplementedZeekAnalysisServiceServer) ZeekSyntaxCheck(context.Context, *ZeekSyntaxCheckRequest) (*ZeekSyntaxCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ZeekSyntaxCheck not implemented")
}
func (UnimplementedZeekAnalysisServiceServer) mustEmbedUnimplementedZeekAnalysisServiceServer() {}
func (UnimplementedZeekAnalysisServiceServer) testEmbeddedByValue()                             {}

// UnsafeZeekAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZeekAnalysisServiceServer will
// result in compilation errors.
type UnsafeZeekAnalysisServiceServer interface {
	mustEmbedUnimplementedZeekAnalysisServiceServer()
}

func RegisterZeekAnalysisServiceServer(s grpc.ServiceRegistrar, srv ZeekAnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedZeekAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZeekAnalysisService_ServiceDesc, srv)
}

func _ZeekAnalysisService_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeekAnalysisServiceServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZeekAnalysisService_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeekAnalysisServiceServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZeekAnalysisService_AsyncAnalyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsyncAnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeekAnalysisServiceServer).AsyncAnalyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZeekAnalysisService_AsyncAnalyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeekAnalysisServiceServer).AsyncAnalyze(ctx, req.(*AsyncAnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZeekAnalysisService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeekAnalysisServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZeekAnalysisService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeekAnalysisServiceServer).GetTaskStatus(ctx, req.(*TaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZeekAnalysisService_GetParentTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParentTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeekAnalysisServiceServer).GetParentTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZeekAnalysisService_GetParentTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeekAnalysisServiceServer).GetParentTaskStatus(ctx, req.(*ParentTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZeekAnalysisService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeekAnalysisServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZeekAnalysisService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeekAnalysisServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZeekAnalysisService_VersionCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeekAnalysisServiceServer).VersionCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZeekAnalysisService_VersionCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeekAnalysisServiceServer).VersionCheck(ctx, req.(*VersionCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZeekAnalysisService_ZeekSyntaxCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZeekSyntaxCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeekAnalysisServiceServer).ZeekSyntaxCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZeekAnalysisService_ZeekSyntaxCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeekAnalysisServiceServer).ZeekSyntaxCheck(ctx, req.(*ZeekSyntaxCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZeekAnalysisService_ServiceDesc is the grpc.ServiceDesc for ZeekAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZeekAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zeek_runner.ZeekAnalysisService",
	HandlerType: (*ZeekAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _ZeekAnalysisService_Analyze_Handler,
		},
		{
			MethodName: "AsyncAnalyze",
			Handler:    _ZeekAnalysisService_AsyncAnalyze_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _ZeekAnalysisService_GetTaskStatus_Handler,
		},
		{
			MethodName: "GetParentTaskStatus",
			Handler:    _ZeekAnalysisService_GetParentTaskStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ZeekAnalysisService_HealthCheck_Handler,
		},
		{
			MethodName: "VersionCheck",
			Handler:    _ZeekAnalysisService_VersionCheck_Handler,
		},
		{
			MethodName: "ZeekSyntaxCheck",
			Handler:    _ZeekAnalysisService_ZeekSyntaxCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/zeek_runner.proto",
}
