// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/pb/zeek_runner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求体
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`          // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`              // UUID
	OnlyNotice    bool                   `protobuf:"varint,3,opt,name=onlyNotice,proto3" json:"onlyNotice,omitempty"` // 是否只生成notice日志
	PcapID        string                 `protobuf:"bytes,4,opt,name=pcapID,proto3" json:"pcapID,omitempty"`          // pcap文件ID
	PcapPath      string                 `protobuf:"bytes,5,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`      // pcap文件路径
	ScriptID      string                 `protobuf:"bytes,6,opt,name=scriptID,proto3" json:"scriptID,omitempty"`      // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,7,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`  // 脚本路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AnalyzeRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AnalyzeRequest) GetOnlyNotice() bool {
	if x != nil {
		return x.OnlyNotice
	}
	return false
}

func (x *AnalyzeRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *AnalyzeRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AnalyzeRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *AnalyzeRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

// 响应体
type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	PcapPath      string                 `protobuf:"bytes,3,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`     // pcap文件路径
	ScriptPath    string                 `protobuf:"bytes,4,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"` // 脚本路径
	StartTime     string                 `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`   // 任务开始时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AnalyzeResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AnalyzeResponse) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AnalyzeResponse) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *AnalyzeResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

// 文件提取请求
type ExtractRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskID               string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`                              // 任务ID
	Uuid                 string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                                  // UUID
	PcapID               string                 `protobuf:"bytes,3,opt,name=pcapID,proto3" json:"pcapID,omitempty"`                              // pcap文件ID
	PcapPath             string                 `protobuf:"bytes,4,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`                          // pcap文件路径
	ScriptPath           string                 `protobuf:"bytes,5,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`                      // 脚本路径（可选，绝对路径）
	OutputDir            string                 `protobuf:"bytes,6,opt,name=outputDir,proto3" json:"outputDir,omitempty"`                        // 提取文件存储路径
	ExtractedFileMinSize int32                  `protobuf:"varint,7,opt,name=extractedFileMinSize,proto3" json:"extractedFileMinSize,omitempty"` // 提取文件最小大小(KB)
	ExtractedFileMaxSize int32                  `protobuf:"varint,8,opt,name=extractedFileMaxSize,proto3" json:"extractedFileMaxSize,omitempty"` // 提取文件最大大小(MB)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExtractRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExtractRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *ExtractRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *ExtractRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ExtractRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ExtractRequest) GetExtractedFileMinSize() int32 {
	if x != nil {
		return x.ExtractedFileMinSize
	}
	return 0
}

func (x *ExtractRequest) GetExtractedFileMaxSize() int32 {
	if x != nil {
		return x.ExtractedFileMaxSize
	}
	return 0
}

// 文件提取响应
type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	PcapPath      string                 `protobuf:"bytes,3,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`     // pcap文件路径
	ScriptPath    string                 `protobuf:"bytes,4,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"` // 脚本路径
	OutputDir     string                 `protobuf:"bytes,5,opt,name=outputDir,proto3" json:"outputDir,omitempty"`   // 提取文件存储路径
	StartTime     string                 `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`   // 任务开始时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExtractResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExtractResponse) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *ExtractResponse) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ExtractResponse) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ExtractResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

// 容量检查请求
type CapacityCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityCheckRequest) Reset() {
	*x = CapacityCheckRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityCheckRequest) ProtoMessage() {}

func (x *CapacityCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityCheckRequest.ProtoReflect.Descriptor instead.
func (*CapacityCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{4}
}

// 容量检查响应：仅暴露真实可用于背压的字段
type CapacityCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AcceptingJobs    bool                   `protobuf:"varint,1,opt,name=accepting_jobs,json=acceptingJobs,proto3" json:"accepting_jobs,omitempty"`          // 是否仍在接收任务
	PoolRunning      int32                  `protobuf:"varint,2,opt,name=pool_running,json=poolRunning,proto3" json:"pool_running,omitempty"`                // ants worker pool 实际运行量
	PoolCapacity     int32                  `protobuf:"varint,3,opt,name=pool_capacity,json=poolCapacity,proto3" json:"pool_capacity,omitempty"`             // ants worker pool 容量
	WeightedRunning  int32                  `protobuf:"varint,4,opt,name=weighted_running,json=weightedRunning,proto3" json:"weighted_running,omitempty"`    // 当前异步 batch 已占用的本地资源权重
	WeightedCapacity int32                  `protobuf:"varint,5,opt,name=weighted_capacity,json=weightedCapacity,proto3" json:"weighted_capacity,omitempty"` // 本地权重上限
	QueuePending     int64                  `protobuf:"varint,6,opt,name=queue_pending,json=queuePending,proto3" json:"queue_pending,omitempty"`             // Redis Stream 中未领取的真实等待量 (XLEN - XPENDING)
	Timestamp        string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapacityCheckResponse) Reset() {
	*x = CapacityCheckResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityCheckResponse) ProtoMessage() {}

func (x *CapacityCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityCheckResponse.ProtoReflect.Descriptor instead.
func (*CapacityCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{5}
}

func (x *CapacityCheckResponse) GetAcceptingJobs() bool {
	if x != nil {
		return x.AcceptingJobs
	}
	return false
}

func (x *CapacityCheckResponse) GetPoolRunning() int32 {
	if x != nil {
		return x.PoolRunning
	}
	return 0
}

func (x *CapacityCheckResponse) GetPoolCapacity() int32 {
	if x != nil {
		return x.PoolCapacity
	}
	return 0
}

func (x *CapacityCheckResponse) GetWeightedRunning() int32 {
	if x != nil {
		return x.WeightedRunning
	}
	return 0
}

func (x *CapacityCheckResponse) GetWeightedCapacity() int32 {
	if x != nil {
		return x.WeightedCapacity
	}
	return 0
}

func (x *CapacityCheckResponse) GetQueuePending() int64 {
	if x != nil {
		return x.QueuePending
	}
	return 0
}

func (x *CapacityCheckResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 版本检查请求
type VersionCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // 组件名称，目前支持 zeek
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionCheckRequest) Reset() {
	*x = VersionCheckRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionCheckRequest) ProtoMessage() {}

func (x *VersionCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionCheckRequest.ProtoReflect.Descriptor instead.
func (*VersionCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{6}
}

func (x *VersionCheckRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

// 版本检查响应
type VersionCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // 组件名称
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`     // 版本信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionCheckResponse) Reset() {
	*x = VersionCheckResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionCheckResponse) ProtoMessage() {}

func (x *VersionCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionCheckResponse.ProtoReflect.Descriptor instead.
func (*VersionCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{7}
}

func (x *VersionCheckResponse) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *VersionCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ZeekSyntaxCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptID      string                 `protobuf:"bytes,1,opt,name=scriptID,proto3" json:"scriptID,omitempty"`           // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,2,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`       // 脚本路径
	ScriptContent string                 `protobuf:"bytes,3,opt,name=scriptContent,proto3" json:"scriptContent,omitempty"` // 脚本内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeekSyntaxCheckRequest) Reset() {
	*x = ZeekSyntaxCheckRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeekSyntaxCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeekSyntaxCheckRequest) ProtoMessage() {}

func (x *ZeekSyntaxCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeekSyntaxCheckRequest.ProtoReflect.Descriptor instead.
func (*ZeekSyntaxCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{8}
}

func (x *ZeekSyntaxCheckRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *ZeekSyntaxCheckRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ZeekSyntaxCheckRequest) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

type ZeekSyntaxCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"` // 是否有效
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`  // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeekSyntaxCheckResponse) Reset() {
	*x = ZeekSyntaxCheckResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeekSyntaxCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeekSyntaxCheckResponse) ProtoMessage() {}

func (x *ZeekSyntaxCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeekSyntaxCheckResponse.ProtoReflect.Descriptor instead.
func (*ZeekSyntaxCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{9}
}

func (x *ZeekSyntaxCheckResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ZeekSyntaxCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AsyncAnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`          // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`              // UUID
	OnlyNotice    bool                   `protobuf:"varint,3,opt,name=onlyNotice,proto3" json:"onlyNotice,omitempty"` // 是否只生成notice日志
	PcapID        string                 `protobuf:"bytes,4,opt,name=pcapID,proto3" json:"pcapID,omitempty"`          // pcap文件ID
	PcapPath      string                 `protobuf:"bytes,5,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`      // pcap文件路径
	ScriptID      string                 `protobuf:"bytes,6,opt,name=scriptID,proto3" json:"scriptID,omitempty"`      // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,7,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`  // 脚本路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncAnalyzeRequest) Reset() {
	*x = AsyncAnalyzeRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncAnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncAnalyzeRequest) ProtoMessage() {}

func (x *AsyncAnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncAnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AsyncAnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{10}
}

func (x *AsyncAnalyzeRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetOnlyNotice() bool {
	if x != nil {
		return x.OnlyNotice
	}
	return false
}

func (x *AsyncAnalyzeRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

// 异步分析响应
type AsyncAnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`         // 任务状态
	CreateTime    string                 `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncAnalyzeResponse) Reset() {
	*x = AsyncAnalyzeResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncAnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncAnalyzeResponse) ProtoMessage() {}

func (x *AsyncAnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncAnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AsyncAnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{11}
}

func (x *AsyncAnalyzeResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AsyncAnalyzeResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AsyncAnalyzeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AsyncAnalyzeResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type ScriptTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`             // 子任务UUID
	ScriptID      string                 `protobuf:"bytes,2,opt,name=scriptID,proto3" json:"scriptID,omitempty"`     // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,3,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"` // 脚本路径（可选，优先使用托管脚本）
	RunMode       string                 `protobuf:"bytes,4,opt,name=runMode,proto3" json:"runMode,omitempty"`       // 运行模式：scan/intel/extract
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`        // 调度权重
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptTask) Reset() {
	*x = ScriptTask{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptTask) ProtoMessage() {}

func (x *ScriptTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptTask.ProtoReflect.Descriptor instead.
func (*ScriptTask) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{12}
}

func (x *ScriptTask) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ScriptTask) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *ScriptTask) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ScriptTask) GetRunMode() string {
	if x != nil {
		return x.RunMode
	}
	return ""
}

func (x *ScriptTask) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type AsyncAnalyzeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`          // 父任务ID
	PcapID        string                 `protobuf:"bytes,2,opt,name=pcapID,proto3" json:"pcapID,omitempty"`          // pcap文件ID
	PcapPath      string                 `protobuf:"bytes,3,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`      // pcap文件路径
	OnlyNotice    bool                   `protobuf:"varint,4,opt,name=onlyNotice,proto3" json:"onlyNotice,omitempty"` // 是否只生成notice日志
	Scripts       []*ScriptTask          `protobuf:"bytes,5,rep,name=scripts,proto3" json:"scripts,omitempty"`        // 脚本任务列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncAnalyzeBatchRequest) Reset() {
	*x = AsyncAnalyzeBatchRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncAnalyzeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncAnalyzeBatchRequest) ProtoMessage() {}

func (x *AsyncAnalyzeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncAnalyzeBatchRequest.ProtoReflect.Descriptor instead.
func (*AsyncAnalyzeBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{13}
}

func (x *AsyncAnalyzeBatchRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AsyncAnalyzeBatchRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *AsyncAnalyzeBatchRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AsyncAnalyzeBatchRequest) GetOnlyNotice() bool {
	if x != nil {
		return x.OnlyNotice
	}
	return false
}

func (x *AsyncAnalyzeBatchRequest) GetScripts() []*ScriptTask {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type AsyncAnalyzeBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`                // 父任务ID
	AcceptedCount int32                  `protobuf:"varint,2,opt,name=acceptedCount,proto3" json:"acceptedCount,omitempty"` // 已接受子任务数
	RejectedCount int32                  `protobuf:"varint,3,opt,name=rejectedCount,proto3" json:"rejectedCount,omitempty"` // 拒绝子任务数
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncAnalyzeBatchResponse) Reset() {
	*x = AsyncAnalyzeBatchResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncAnalyzeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncAnalyzeBatchResponse) ProtoMessage() {}

func (x *AsyncAnalyzeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncAnalyzeBatchResponse.ProtoReflect.Descriptor instead.
func (*AsyncAnalyzeBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{14}
}

func (x *AsyncAnalyzeBatchResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AsyncAnalyzeBatchResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *AsyncAnalyzeBatchResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *AsyncAnalyzeBatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 异步文件提取请求
type ExtractAsyncRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskID               string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`                              // 任务ID
	Uuid                 string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                                  // UUID
	PcapID               string                 `protobuf:"bytes,3,opt,name=pcapID,proto3" json:"pcapID,omitempty"`                              // pcap文件ID
	PcapPath             string                 `protobuf:"bytes,4,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`                          // pcap文件路径
	ScriptPath           string                 `protobuf:"bytes,5,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`                      // 脚本路径（可选，绝对路径）
	OutputDir            string                 `protobuf:"bytes,6,opt,name=outputDir,proto3" json:"outputDir,omitempty"`                        // 提取文件存储路径
	ExtractedFileMinSize int32                  `protobuf:"varint,7,opt,name=extractedFileMinSize,proto3" json:"extractedFileMinSize,omitempty"` // 提取文件最小大小(KB)
	ExtractedFileMaxSize int32                  `protobuf:"varint,8,opt,name=extractedFileMaxSize,proto3" json:"extractedFileMaxSize,omitempty"` // 提取文件最大大小(MB)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExtractAsyncRequest) Reset() {
	*x = ExtractAsyncRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractAsyncRequest) ProtoMessage() {}

func (x *ExtractAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractAsyncRequest.ProtoReflect.Descriptor instead.
func (*ExtractAsyncRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{15}
}

func (x *ExtractAsyncRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExtractAsyncRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExtractAsyncRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *ExtractAsyncRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *ExtractAsyncRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ExtractAsyncRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ExtractAsyncRequest) GetExtractedFileMinSize() int32 {
	if x != nil {
		return x.ExtractedFileMinSize
	}
	return 0
}

func (x *ExtractAsyncRequest) GetExtractedFileMaxSize() int32 {
	if x != nil {
		return x.ExtractedFileMaxSize
	}
	return 0
}

// 异步文件提取响应
type ExtractAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`         // 任务状态
	CreateTime    string                 `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractAsyncResponse) Reset() {
	*x = ExtractAsyncResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractAsyncResponse) ProtoMessage() {}

func (x *ExtractAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractAsyncResponse.ProtoReflect.Descriptor instead.
func (*ExtractAsyncResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{16}
}

func (x *ExtractAsyncResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExtractAsyncResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExtractAsyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExtractAsyncResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 任务状态查询请求
type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 子任务UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{17}
}

func (x *TaskStatusRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 任务状态查询响应
type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`             // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                 // UUID
	PcapID        string                 `protobuf:"bytes,3,opt,name=pcapID,proto3" json:"pcapID,omitempty"`             // pcap文件ID
	PcapPath      string                 `protobuf:"bytes,4,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`         // pcap文件路径
	ScriptID      string                 `protobuf:"bytes,5,opt,name=scriptID,proto3" json:"scriptID,omitempty"`         // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,6,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`     // 脚本路径
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`             // 任务状态
	CreateTime    string                 `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`     // 创建时间
	StartTime     string                 `protobuf:"bytes,9,opt,name=startTime,proto3" json:"startTime,omitempty"`       // 开始时间
	EndTime       string                 `protobuf:"bytes,10,opt,name=endTime,proto3" json:"endTime,omitempty"`          // 结束时间
	Duration      float64                `protobuf:"fixed64,11,opt,name=duration,proto3" json:"duration,omitempty"`      // 执行时长(秒)
	HitCount      int32                  `protobuf:"varint,12,opt,name=hitCount,proto3" json:"hitCount,omitempty"`       // 命中总数
	NoticeCount   int32                  `protobuf:"varint,13,opt,name=noticeCount,proto3" json:"noticeCount,omitempty"` // notice日志数
	IntelCount    int32                  `protobuf:"varint,14,opt,name=intelCount,proto3" json:"intelCount,omitempty"`   // intel日志数
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`              // 错误信息
	Output        string                 `protobuf:"bytes,16,opt,name=output,proto3" json:"output,omitempty"`            // 输出内容
	Retries       int32                  `protobuf:"varint,17,opt,name=retries,proto3" json:"retries,omitempty"`         // 重试次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{18}
}

func (x *TaskStatusResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskStatusResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TaskStatusResponse) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *TaskStatusResponse) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *TaskStatusResponse) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *TaskStatusResponse) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *TaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatusResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *TaskStatusResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TaskStatusResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TaskStatusResponse) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TaskStatusResponse) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *TaskStatusResponse) GetNoticeCount() int32 {
	if x != nil {
		return x.NoticeCount
	}
	return 0
}

func (x *TaskStatusResponse) GetIntelCount() int32 {
	if x != nil {
		return x.IntelCount
	}
	return 0
}

func (x *TaskStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskStatusResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskStatusResponse) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

// 父任务状态查询请求
type ParentTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"` // 父任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentTaskStatusRequest) Reset() {
	*x = ParentTaskStatusRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentTaskStatusRequest) ProtoMessage() {}

func (x *ParentTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*ParentTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{19}
}

func (x *ParentTaskStatusRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

// 子任务摘要
type SubTaskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                // 子任务UUID
	ScriptID      string                 `protobuf:"bytes,2,opt,name=scriptID,proto3" json:"scriptID,omitempty"`        // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,3,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`    // 脚本路径
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`            // 状态
	Duration      float64                `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`      // 执行时长(秒)
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`              // 错误信息
	HitCount      int32                  `protobuf:"varint,7,opt,name=hitCount,proto3" json:"hitCount,omitempty"`       // 命中总数
	NoticeCount   int32                  `protobuf:"varint,8,opt,name=noticeCount,proto3" json:"noticeCount,omitempty"` // notice日志数
	IntelCount    int32                  `protobuf:"varint,9,opt,name=intelCount,proto3" json:"intelCount,omitempty"`   // intel日志数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubTaskSummary) Reset() {
	*x = SubTaskSummary{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubTaskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTaskSummary) ProtoMessage() {}

func (x *SubTaskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubTaskSummary.ProtoReflect.Descriptor instead.
func (*SubTaskSummary) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{20}
}

func (x *SubTaskSummary) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SubTaskSummary) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *SubTaskSummary) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *SubTaskSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubTaskSummary) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SubTaskSummary) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SubTaskSummary) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *SubTaskSummary) GetNoticeCount() int32 {
	if x != nil {
		return x.NoticeCount
	}
	return 0
}

func (x *SubTaskSummary) GetIntelCount() int32 {
	if x != nil {
		return x.IntelCount
	}
	return 0
}

// 父任务状态查询响应
type ParentTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`              // 父任务ID
	TotalCount    int32                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`     // 总子任务数
	PendingCount  int32                  `protobuf:"varint,3,opt,name=pendingCount,proto3" json:"pendingCount,omitempty"` // 待处理数
	RunningCount  int32                  `protobuf:"varint,4,opt,name=runningCount,proto3" json:"runningCount,omitempty"` // 运行中数
	SuccessCount  int32                  `protobuf:"varint,5,opt,name=successCount,proto3" json:"successCount,omitempty"` // 成功数
	FailedCount   int32                  `protobuf:"varint,6,opt,name=failedCount,proto3" json:"failedCount,omitempty"`   // 失败数
	TimeoutCount  int32                  `protobuf:"varint,7,opt,name=timeoutCount,proto3" json:"timeoutCount,omitempty"` // 超时数
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`              // 聚合状态: pending/running/completed/partial_failed/failed
	SubTasks      []*SubTaskSummary      `protobuf:"bytes,9,rep,name=subTasks,proto3" json:"subTasks,omitempty"`          // 子任务列表
	HitCount      int32                  `protobuf:"varint,10,opt,name=hitCount,proto3" json:"hitCount,omitempty"`        // 所有子任务命中总数
	NoticeCount   int32                  `protobuf:"varint,11,opt,name=noticeCount,proto3" json:"noticeCount,omitempty"`  // 所有子任务notice日志总数
	IntelCount    int32                  `protobuf:"varint,12,opt,name=intelCount,proto3" json:"intelCount,omitempty"`    // 所有子任务intel日志总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentTaskStatusResponse) Reset() {
	*x = ParentTaskStatusResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentTaskStatusResponse) ProtoMessage() {}

func (x *ParentTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*ParentTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{21}
}

func (x *ParentTaskStatusResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ParentTaskStatusResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetPendingCount() int32 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetRunningCount() int32 {
	if x != nil {
		return x.RunningCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetTimeoutCount() int32 {
	if x != nil {
		return x.TimeoutCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ParentTaskStatusResponse) GetSubTasks() []*SubTaskSummary {
	if x != nil {
		return x.SubTasks
	}
	return nil
}

func (x *ParentTaskStatusResponse) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetNoticeCount() int32 {
	if x != nil {
		return x.NoticeCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetIntelCount() int32 {
	if x != nil {
		return x.IntelCount
	}
	return 0
}

type ListScriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnabledOnly   bool                   `protobuf:"varint,2,opt,name=enabledOnly,proto3" json:"enabledOnly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsRequest) Reset() {
	*x = ListScriptsRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsRequest) ProtoMessage() {}

func (x *ListScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsRequest.ProtoReflect.Descriptor instead.
func (*ListScriptsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{22}
}

func (x *ListScriptsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListScriptsRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ScriptInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScriptID         string                 `protobuf:"bytes,1,opt,name=scriptID,proto3" json:"scriptID,omitempty"`
	ScriptName       string                 `protobuf:"bytes,2,opt,name=scriptName,proto3" json:"scriptName,omitempty"`
	ScriptPath       string                 `protobuf:"bytes,3,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`
	ExpCodeType      string                 `protobuf:"bytes,4,opt,name=expCodeType,proto3" json:"expCodeType,omitempty"`
	Size             string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	BehaviorType     string                 `protobuf:"bytes,6,opt,name=behaviorType,proto3" json:"behaviorType,omitempty"`
	BehaviorCategory string                 `protobuf:"bytes,7,opt,name=behaviorCategory,proto3" json:"behaviorCategory,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	AttackFeature    string                 `protobuf:"bytes,9,opt,name=attackFeature,proto3" json:"attackFeature,omitempty"`
	Checksum         string                 `protobuf:"bytes,10,opt,name=checksum,proto3" json:"checksum,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Enabled          bool                   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Valid            bool                   `protobuf:"varint,13,opt,name=valid,proto3" json:"valid,omitempty"`
	Error            string                 `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	NoticeTypes      []string               `protobuf:"bytes,15,rep,name=noticeTypes,proto3" json:"noticeTypes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScriptInfo) Reset() {
	*x = ScriptInfo{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptInfo) ProtoMessage() {}

func (x *ScriptInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptInfo.ProtoReflect.Descriptor instead.
func (*ScriptInfo) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{23}
}

func (x *ScriptInfo) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *ScriptInfo) GetScriptName() string {
	if x != nil {
		return x.ScriptName
	}
	return ""
}

func (x *ScriptInfo) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ScriptInfo) GetExpCodeType() string {
	if x != nil {
		return x.ExpCodeType
	}
	return ""
}

func (x *ScriptInfo) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ScriptInfo) GetBehaviorType() string {
	if x != nil {
		return x.BehaviorType
	}
	return ""
}

func (x *ScriptInfo) GetBehaviorCategory() string {
	if x != nil {
		return x.BehaviorCategory
	}
	return ""
}

func (x *ScriptInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScriptInfo) GetAttackFeature() string {
	if x != nil {
		return x.AttackFeature
	}
	return ""
}

func (x *ScriptInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ScriptInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ScriptInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScriptInfo) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ScriptInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScriptInfo) GetNoticeTypes() []string {
	if x != nil {
		return x.NoticeTypes
	}
	return nil
}

type ListScriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scripts       []*ScriptInfo          `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsResponse) Reset() {
	*x = ListScriptsResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsResponse) ProtoMessage() {}

func (x *ListScriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsResponse.ProtoReflect.Descriptor instead.
func (*ListScriptsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{24}
}

func (x *ListScriptsResponse) GetScripts() []*ScriptInfo {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type GetScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptID      string                 `protobuf:"bytes,1,opt,name=scriptID,proto3" json:"scriptID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScriptRequest) Reset() {
	*x = GetScriptRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScriptRequest) ProtoMessage() {}

func (x *GetScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScriptRequest.ProtoReflect.Descriptor instead.
func (*GetScriptRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{25}
}

func (x *GetScriptRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

type ReloadScriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadScriptsRequest) Reset() {
	*x = ReloadScriptsRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadScriptsRequest) ProtoMessage() {}

func (x *ReloadScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadScriptsRequest.ProtoReflect.Descriptor instead.
func (*ReloadScriptsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{26}
}

type ReloadScriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Valid         int32                  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Invalid       int32                  `protobuf:"varint,3,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Scripts       []*ScriptInfo          `protobuf:"bytes,4,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadScriptsResponse) Reset() {
	*x = ReloadScriptsResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadScriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadScriptsResponse) ProtoMessage() {}

func (x *ReloadScriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadScriptsResponse.ProtoReflect.Descriptor instead.
func (*ReloadScriptsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{27}
}

func (x *ReloadScriptsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ReloadScriptsResponse) GetValid() int32 {
	if x != nil {
		return x.Valid
	}
	return 0
}

func (x *ReloadScriptsResponse) GetInvalid() int32 {
	if x != nil {
		return x.Invalid
	}
	return 0
}

func (x *ReloadScriptsResponse) GetScripts() []*ScriptInfo {
	if x != nil {
		return x.Scripts
	}
	return nil
}

// 行为规则策略由外部控制面下发。规则 YAML 的内容与 SHA 不变，
// 仅按厂商配置状态过滤运行时行为规则。
type ApplyBehaviorPolicyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DisabledVendorIds []string               `protobuf:"bytes,1,rep,name=disabled_vendor_ids,json=disabledVendorIds,proto3" json:"disabled_vendor_ids,omitempty"`
	PolicyVersion     string                 `protobuf:"bytes,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplyBehaviorPolicyRequest) Reset() {
	*x = ApplyBehaviorPolicyRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBehaviorPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBehaviorPolicyRequest) ProtoMessage() {}

func (x *ApplyBehaviorPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBehaviorPolicyRequest.ProtoReflect.Descriptor instead.
func (*ApplyBehaviorPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{28}
}

func (x *ApplyBehaviorPolicyRequest) GetDisabledVendorIds() []string {
	if x != nil {
		return x.DisabledVendorIds
	}
	return nil
}

func (x *ApplyBehaviorPolicyRequest) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type ApplyBehaviorPolicyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EffectiveRuleCount int32                  `protobuf:"varint,1,opt,name=effective_rule_count,json=effectiveRuleCount,proto3" json:"effective_rule_count,omitempty"`
	DisabledVendorIds  []string               `protobuf:"bytes,2,rep,name=disabled_vendor_ids,json=disabledVendorIds,proto3" json:"disabled_vendor_ids,omitempty"`
	RulesetSha256      string                 `protobuf:"bytes,3,opt,name=ruleset_sha256,json=rulesetSha256,proto3" json:"ruleset_sha256,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplyBehaviorPolicyResponse) Reset() {
	*x = ApplyBehaviorPolicyResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBehaviorPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBehaviorPolicyResponse) ProtoMessage() {}

func (x *ApplyBehaviorPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBehaviorPolicyResponse.ProtoReflect.Descriptor instead.
func (*ApplyBehaviorPolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{29}
}

func (x *ApplyBehaviorPolicyResponse) GetEffectiveRuleCount() int32 {
	if x != nil {
		return x.EffectiveRuleCount
	}
	return 0
}

func (x *ApplyBehaviorPolicyResponse) GetDisabledVendorIds() []string {
	if x != nil {
		return x.DisabledVendorIds
	}
	return nil
}

func (x *ApplyBehaviorPolicyResponse) GetRulesetSha256() string {
	if x != nil {
		return x.RulesetSha256
	}
	return ""
}

// 任务命中详情查询请求
type GetTaskHitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`             // 子任务UUID
	TaskID        string                 `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 父任务ID（可选，按父任务查询所有子任务命中）
	SourceType    string                 `protobuf:"bytes,3,opt,name=sourceType,proto3" json:"sourceType,omitempty"` // 过滤：notice 或 intel（可选）
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`          // 返回数量限制（默认100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskHitsRequest) Reset() {
	*x = GetTaskHitsRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskHitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskHitsRequest) ProtoMessage() {}

func (x *GetTaskHitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskHitsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskHitsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{30}
}

func (x *GetTaskHitsRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetTaskHitsRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *GetTaskHitsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *GetTaskHitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 单条命中事件
type HitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=eventType,proto3" json:"eventType,omitempty"`
	EventTime     string                 `protobuf:"bytes,3,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	TaskID        string                 `protobuf:"bytes,4,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PcapID        string                 `protobuf:"bytes,6,opt,name=pcapID,proto3" json:"pcapID,omitempty"`
	PcapPath      string                 `protobuf:"bytes,7,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`
	ScriptID      string                 `protobuf:"bytes,8,opt,name=scriptID,proto3" json:"scriptID,omitempty"`
	ScriptPath    string                 `protobuf:"bytes,9,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`
	Verdict       string                 `protobuf:"bytes,10,opt,name=verdict,proto3" json:"verdict,omitempty"`
	SourceType    string                 `protobuf:"bytes,11,opt,name=sourceType,proto3" json:"sourceType,omitempty"` // notice 或 intel
	RuleType      string                 `protobuf:"bytes,12,opt,name=ruleType,proto3" json:"ruleType,omitempty"`     // notice类型 或 intel where
	RuleName      string                 `protobuf:"bytes,13,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	Message       string                 `protobuf:"bytes,14,opt,name=message,proto3" json:"message,omitempty"`
	Indicator     string                 `protobuf:"bytes,15,opt,name=indicator,proto3" json:"indicator,omitempty"`
	SrcIp         string                 `protobuf:"bytes,16,opt,name=srcIp,proto3" json:"srcIp,omitempty"`
	SrcPort       int32                  `protobuf:"varint,17,opt,name=srcPort,proto3" json:"srcPort,omitempty"`
	DstIp         string                 `protobuf:"bytes,18,opt,name=dstIp,proto3" json:"dstIp,omitempty"`
	DstPort       int32                  `protobuf:"varint,19,opt,name=dstPort,proto3" json:"dstPort,omitempty"`
	Proto         string                 `protobuf:"bytes,20,opt,name=proto,proto3" json:"proto,omitempty"`
	Uid           string                 `protobuf:"bytes,21,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitEvent) Reset() {
	*x = HitEvent{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitEvent) ProtoMessage() {}

func (x *HitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitEvent.ProtoReflect.Descriptor instead.
func (*HitEvent) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{31}
}

func (x *HitEvent) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *HitEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HitEvent) GetEventTime() string {
	if x != nil {
		return x.EventTime
	}
	return ""
}

func (x *HitEvent) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *HitEvent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *HitEvent) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *HitEvent) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *HitEvent) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *HitEvent) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *HitEvent) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *HitEvent) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *HitEvent) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *HitEvent) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *HitEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HitEvent) GetIndicator() string {
	if x != nil {
		return x.Indicator
	}
	return ""
}

func (x *HitEvent) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *HitEvent) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *HitEvent) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *HitEvent) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *HitEvent) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *HitEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// 任务命中详情查询响应
type GetTaskHitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TaskID        string                 `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Hits          []*HitEvent            `protobuf:"bytes,4,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskHitsResponse) Reset() {
	*x = GetTaskHitsResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskHitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskHitsResponse) ProtoMessage() {}

func (x *GetTaskHitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskHitsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskHitsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{32}
}

func (x *GetTaskHitsResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetTaskHitsResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *GetTaskHitsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetTaskHitsResponse) GetHits() []*HitEvent {
	if x != nil {
		return x.Hits
	}
	return nil
}

var File_api_pb_zeek_runner_proto protoreflect.FileDescriptor

const file_api_pb_zeek_runner_proto_rawDesc = "" +
	"\n" +
	"\x18api/pb/zeek_runner.proto\x12\vzeek_runner\"\xcc\x01\n" +
	"\x0eAnalyzeRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"onlyNotice\x18\x03 \x01(\bR\n" +
	"onlyNotice\x12\x16\n" +
	"\x06pcapID\x18\x04 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x05 \x01(\tR\bpcapPath\x12\x1a\n" +
	"\bscriptID\x18\x06 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\a \x01(\tR\n" +
	"scriptPath\"\x97\x01\n" +
	"\x0fAnalyzeResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpcapPath\x18\x03 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x04 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\"\x96\x02\n" +
	"\x0eExtractRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06pcapID\x18\x03 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x04 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x05 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\toutputDir\x18\x06 \x01(\tR\toutputDir\x122\n" +
	"\x14extractedFileMinSize\x18\a \x01(\x05R\x14extractedFileMinSize\x122\n" +
	"\x14extractedFileMaxSize\x18\b \x01(\x05R\x14extractedFileMaxSize\"\xb5\x01\n" +
	"\x0fExtractResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpcapPath\x18\x03 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x04 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\toutputDir\x18\x05 \x01(\tR\toutputDir\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\tR\tstartTime\"\x16\n" +
	"\x14CapacityCheckRequest\"\xa1\x02\n" +
	"\x15CapacityCheckResponse\x12%\n" +
	"\x0eaccepting_jobs\x18\x01 \x01(\bR\racceptingJobs\x12!\n" +
	"\fpool_running\x18\x02 \x01(\x05R\vpoolRunning\x12#\n" +
	"\rpool_capacity\x18\x03 \x01(\x05R\fpoolCapacity\x12)\n" +
	"\x10weighted_running\x18\x04 \x01(\x05R\x0fweightedRunning\x12+\n" +
	"\x11weighted_capacity\x18\x05 \x01(\x05R\x10weightedCapacity\x12#\n" +
	"\rqueue_pending\x18\x06 \x01(\x03R\fqueuePending\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\"3\n" +
	"\x13VersionCheckRequest\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\"N\n" +
	"\x14VersionCheckResponse\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"z\n" +
	"\x16ZeekSyntaxCheckRequest\x12\x1a\n" +
	"\bscriptID\x18\x01 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x02 \x01(\tR\n" +
	"scriptPath\x12$\n" +
	"\rscriptContent\x18\x03 \x01(\tR\rscriptContent\"E\n" +
	"\x17ZeekSyntaxCheckResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd1\x01\n" +
	"\x13AsyncAnalyzeRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"onlyNotice\x18\x03 \x01(\bR\n" +
	"onlyNotice\x12\x16\n" +
	"\x06pcapID\x18\x04 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x05 \x01(\tR\bpcapPath\x12\x1a\n" +
	"\bscriptID\x18\x06 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\a \x01(\tR\n" +
	"scriptPath\"z\n" +
	"\x14AsyncAnalyzeResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\tR\n" +
	"createTime\"\x8e\x01\n" +
	"\n" +
	"ScriptTask\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bscriptID\x18\x02 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x03 \x01(\tR\n" +
	"scriptPath\x12\x18\n" +
	"\arunMode\x18\x04 \x01(\tR\arunMode\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\"\xb9\x01\n" +
	"\x18AsyncAnalyzeBatchRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x16\n" +
	"\x06pcapID\x18\x02 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x03 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"onlyNotice\x18\x04 \x01(\bR\n" +
	"onlyNotice\x121\n" +
	"\ascripts\x18\x05 \x03(\v2\x17.zeek_runner.ScriptTaskR\ascripts\"\x97\x01\n" +
	"\x19AsyncAnalyzeBatchResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12$\n" +
	"\racceptedCount\x18\x02 \x01(\x05R\racceptedCount\x12$\n" +
	"\rrejectedCount\x18\x03 \x01(\x05R\rrejectedCount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x9b\x02\n" +
	"\x13ExtractAsyncRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06pcapID\x18\x03 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x04 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x05 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\toutputDir\x18\x06 \x01(\tR\toutputDir\x122\n" +
	"\x14extractedFileMinSize\x18\a \x01(\x05R\x14extractedFileMinSize\x122\n" +
	"\x14extractedFileMaxSize\x18\b \x01(\x05R\x14extractedFileMaxSize\"z\n" +
	"\x14ExtractAsyncResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\tR\n" +
	"createTime\"'\n" +
	"\x11TaskStatusRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xe2\x03\n" +
	"\x12TaskStatusResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06pcapID\x18\x03 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x04 \x01(\tR\bpcapPath\x12\x1a\n" +
	"\bscriptID\x18\x05 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x06 \x01(\tR\n" +
	"scriptPath\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\tR\n" +
	"createTime\x12\x1c\n" +
	"\tstartTime\x18\t \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\n" +
	" \x01(\tR\aendTime\x12\x1a\n" +
	"\bduration\x18\v \x01(\x01R\bduration\x12\x1a\n" +
	"\bhitCount\x18\f \x01(\x05R\bhitCount\x12 \n" +
	"\vnoticeCount\x18\r \x01(\x05R\vnoticeCount\x12\x1e\n" +
	"\n" +
	"intelCount\x18\x0e \x01(\x05R\n" +
	"intelCount\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x10 \x01(\tR\x06output\x12\x18\n" +
	"\aretries\x18\x11 \x01(\x05R\aretries\"1\n" +
	"\x17ParentTaskStatusRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\"\x88\x02\n" +
	"\x0eSubTaskSummary\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bscriptID\x18\x02 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x03 \x01(\tR\n" +
	"scriptPath\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x01R\bduration\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1a\n" +
	"\bhitCount\x18\a \x01(\x05R\bhitCount\x12 \n" +
	"\vnoticeCount\x18\b \x01(\x05R\vnoticeCount\x12\x1e\n" +
	"\n" +
	"intelCount\x18\t \x01(\x05R\n" +
	"intelCount\"\xb3\x03\n" +
	"\x18ParentTaskStatusResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\"\n" +
	"\fpendingCount\x18\x03 \x01(\x05R\fpendingCount\x12\"\n" +
	"\frunningCount\x18\x04 \x01(\x05R\frunningCount\x12\"\n" +
	"\fsuccessCount\x18\x05 \x01(\x05R\fsuccessCount\x12 \n" +
	"\vfailedCount\x18\x06 \x01(\x05R\vfailedCount\x12\"\n" +
	"\ftimeoutCount\x18\a \x01(\x05R\ftimeoutCount\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x127\n" +
	"\bsubTasks\x18\t \x03(\v2\x1b.zeek_runner.SubTaskSummaryR\bsubTasks\x12\x1a\n" +
	"\bhitCount\x18\n" +
	" \x01(\x05R\bhitCount\x12 \n" +
	"\vnoticeCount\x18\v \x01(\x05R\vnoticeCount\x12\x1e\n" +
	"\n" +
	"intelCount\x18\f \x01(\x05R\n" +
	"intelCount\"J\n" +
	"\x12ListScriptsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\venabledOnly\x18\x02 \x01(\bR\venabledOnly\"\xd8\x03\n" +
	"\n" +
	"ScriptInfo\x12\x1a\n" +
	"\bscriptID\x18\x01 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptName\x18\x02 \x01(\tR\n" +
	"scriptName\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x03 \x01(\tR\n" +
	"scriptPath\x12 \n" +
	"\vexpCodeType\x18\x04 \x01(\tR\vexpCodeType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12\"\n" +
	"\fbehaviorType\x18\x06 \x01(\tR\fbehaviorType\x12*\n" +
	"\x10behaviorCategory\x18\a \x01(\tR\x10behaviorCategory\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12$\n" +
	"\rattackFeature\x18\t \x01(\tR\rattackFeature\x12\x1a\n" +
	"\bchecksum\x18\n" +
	" \x01(\tR\bchecksum\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aenabled\x18\f \x01(\bR\aenabled\x12\x14\n" +
	"\x05valid\x18\r \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x0e \x01(\tR\x05error\x12 \n" +
	"\vnoticeTypes\x18\x0f \x03(\tR\vnoticeTypes\"H\n" +
	"\x13ListScriptsResponse\x121\n" +
	"\ascripts\x18\x01 \x03(\v2\x17.zeek_runner.ScriptInfoR\ascripts\".\n" +
	"\x10GetScriptRequest\x12\x1a\n" +
	"\bscriptID\x18\x01 \x01(\tR\bscriptID\"\x16\n" +
	"\x14ReloadScriptsRequest\"\x90\x01\n" +
	"\x15ReloadScriptsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\x05R\x05valid\x12\x18\n" +
	"\ainvalid\x18\x03 \x01(\x05R\ainvalid\x121\n" +
	"\ascripts\x18\x04 \x03(\v2\x17.zeek_runner.ScriptInfoR\ascripts\"s\n" +
	"\x1aApplyBehaviorPolicyRequest\x12.\n" +
	"\x13disabled_vendor_ids\x18\x01 \x03(\tR\x11disabledVendorIds\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\tR\rpolicyVersion\"\xa6\x01\n" +
	"\x1bApplyBehaviorPolicyResponse\x120\n" +
	"\x14effective_rule_count\x18\x01 \x01(\x05R\x12effectiveRuleCount\x12.\n" +
	"\x13disabled_vendor_ids\x18\x02 \x03(\tR\x11disabledVendorIds\x12%\n" +
	"\x0eruleset_sha256\x18\x03 \x01(\tR\rrulesetSha256\"v\n" +
	"\x12GetTaskHitsRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06taskID\x18\x02 \x01(\tR\x06taskID\x12\x1e\n" +
	"\n" +
	"sourceType\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xae\x04\n" +
	"\bHitEvent\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12\x1c\n" +
	"\teventType\x18\x02 \x01(\tR\teventType\x12\x1c\n" +
	"\teventTime\x18\x03 \x01(\tR\teventTime\x12\x16\n" +
	"\x06taskID\x18\x04 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06pcapID\x18\x06 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\a \x01(\tR\bpcapPath\x12\x1a\n" +
	"\bscriptID\x18\b \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\t \x01(\tR\n" +
	"scriptPath\x12\x18\n" +
	"\averdict\x18\n" +
	" \x01(\tR\averdict\x12\x1e\n" +
	"\n" +
	"sourceType\x18\v \x01(\tR\n" +
	"sourceType\x12\x1a\n" +
	"\bruleType\x18\f \x01(\tR\bruleType\x12\x1a\n" +
	"\bruleName\x18\r \x01(\tR\bruleName\x12\x18\n" +
	"\amessage\x18\x0e \x01(\tR\amessage\x12\x1c\n" +
	"\tindicator\x18\x0f \x01(\tR\tindicator\x12\x14\n" +
	"\x05srcIp\x18\x10 \x01(\tR\x05srcIp\x12\x18\n" +
	"\asrcPort\x18\x11 \x01(\x05R\asrcPort\x12\x14\n" +
	"\x05dstIp\x18\x12 \x01(\tR\x05dstIp\x12\x18\n" +
	"\adstPort\x18\x13 \x01(\x05R\adstPort\x12\x14\n" +
	"\x05proto\x18\x14 \x01(\tR\x05proto\x12\x10\n" +
	"\x03uid\x18\x15 \x01(\tR\x03uid\"\x8c\x01\n" +
	"\x13GetTaskHitsResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06taskID\x18\x02 \x01(\tR\x06taskID\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x03 \x01(\x05R\n" +
	"totalCount\x12)\n" +
	"\x04hits\x18\x04 \x03(\v2\x15.zeek_runner.HitEventR\x04hits2\xb9\n" +
	"\n" +
	"\x13ZeekAnalysisService\x12F\n" +
	"\aAnalyze\x12\x1b.zeek_runner.AnalyzeRequest\x1a\x1c.zeek_runner.AnalyzeResponse\"\x00\x12U\n" +
	"\fAsyncAnalyze\x12 .zeek_runner.AsyncAnalyzeRequest\x1a!.zeek_runner.AsyncAnalyzeResponse\"\x00\x12d\n" +
	"\x11AsyncAnalyzeBatch\x12%.zeek_runner.AsyncAnalyzeBatchRequest\x1a&.zeek_runner.AsyncAnalyzeBatchResponse\"\x00\x12F\n" +
	"\aExtract\x12\x1b.zeek_runner.ExtractRequest\x1a\x1c.zeek_runner.ExtractResponse\"\x00\x12U\n" +
	"\fExtractAsync\x12 .zeek_runner.ExtractAsyncRequest\x1a!.zeek_runner.ExtractAsyncResponse\"\x00\x12R\n" +
	"\rGetTaskStatus\x12\x1e.zeek_runner.TaskStatusRequest\x1a\x1f.zeek_runner.TaskStatusResponse\"\x00\x12d\n" +
	"\x13GetParentTaskStatus\x12$.zeek_runner.ParentTaskStatusRequest\x1a%.zeek_runner.ParentTaskStatusResponse\"\x00\x12X\n" +
	"\rCapacityCheck\x12!.zeek_runner.CapacityCheckRequest\x1a\".zeek_runner.CapacityCheckResponse\"\x00\x12U\n" +
	"\fVersionCheck\x12 .zeek_runner.VersionCheckRequest\x1a!.zeek_runner.VersionCheckResponse\"\x00\x12^\n" +
	"\x0fZeekSyntaxCheck\x12#.zeek_runner.ZeekSyntaxCheckRequest\x1a$.zeek_runner.ZeekSyntaxCheckResponse\"\x00\x12R\n" +
	"\vListScripts\x12\x1f.zeek_runner.ListScriptsRequest\x1a .zeek_runner.ListScriptsResponse\"\x00\x12E\n" +
	"\tGetScript\x12\x1d.zeek_runner.GetScriptRequest\x1a\x17.zeek_runner.ScriptInfo\"\x00\x12X\n" +
	"\rReloadScripts\x12!.zeek_runner.ReloadScriptsRequest\x1a\".zeek_runner.ReloadScriptsResponse\"\x00\x12j\n" +
	"\x13ApplyBehaviorPolicy\x12'.zeek_runner.ApplyBehaviorPolicyRequest\x1a(.zeek_runner.ApplyBehaviorPolicyResponse\"\x00\x12R\n" +
	"\vGetTaskHits\x12\x1f.zeek_runner.GetTaskHitsRequest\x1a .zeek_runner.GetTaskHitsResponse\"\x00B\x14Z\x12zeek_runner/api/pbb\x06proto3"

var (
	file_api_pb_zeek_runner_proto_rawDescOnce sync.Once
	file_api_pb_zeek_runner_proto_rawDescData []byte
)

func file_api_pb_zeek_runner_proto_rawDescGZIP() []byte {
	file_api_pb_zeek_runner_proto_rawDescOnce.Do(func() {
		file_api_pb_zeek_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_zeek_runner_proto_rawDesc), len(file_api_pb_zeek_runner_proto_rawDesc)))
	})
	return file_api_pb_zeek_runner_proto_rawDescData
}

var file_api_pb_zeek_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_api_pb_zeek_runner_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),              // 0: zeek_runner.AnalyzeRequest
	(*AnalyzeResponse)(nil),             // 1: zeek_runner.AnalyzeResponse
	(*ExtractRequest)(nil),              // 2: zeek_runner.ExtractRequest
	(*ExtractResponse)(nil),             // 3: zeek_runner.ExtractResponse
	(*CapacityCheckRequest)(nil),        // 4: zeek_runner.CapacityCheckRequest
	(*CapacityCheckResponse)(nil),       // 5: zeek_runner.CapacityCheckResponse
	(*VersionCheckRequest)(nil),         // 6: zeek_runner.VersionCheckRequest
	(*VersionCheckResponse)(nil),        // 7: zeek_runner.VersionCheckResponse
	(*ZeekSyntaxCheckRequest)(nil),      // 8: zeek_runner.ZeekSyntaxCheckRequest
	(*ZeekSyntaxCheckResponse)(nil),     // 9: zeek_runner.ZeekSyntaxCheckResponse
	(*AsyncAnalyzeRequest)(nil),         // 10: zeek_runner.AsyncAnalyzeRequest
	(*AsyncAnalyzeResponse)(nil),        // 11: zeek_runner.AsyncAnalyzeResponse
	(*ScriptTask)(nil),                  // 12: zeek_runner.ScriptTask
	(*AsyncAnalyzeBatchRequest)(nil),    // 13: zeek_runner.AsyncAnalyzeBatchRequest
	(*AsyncAnalyzeBatchResponse)(nil),   // 14: zeek_runner.AsyncAnalyzeBatchResponse
	(*ExtractAsyncRequest)(nil),         // 15: zeek_runner.ExtractAsyncRequest
	(*ExtractAsyncResponse)(nil),        // 16: zeek_runner.ExtractAsyncResponse
	(*TaskStatusRequest)(nil),           // 17: zeek_runner.TaskStatusRequest
	(*TaskStatusResponse)(nil),          // 18: zeek_runner.TaskStatusResponse
	(*ParentTaskStatusRequest)(nil),     // 19: zeek_runner.ParentTaskStatusRequest
	(*SubTaskSummary)(nil),              // 20: zeek_runner.SubTaskSummary
	(*ParentTaskStatusResponse)(nil),    // 21: zeek_runner.ParentTaskStatusResponse
	(*ListScriptsRequest)(nil),          // 22: zeek_runner.ListScriptsRequest
	(*ScriptInfo)(nil),                  // 23: zeek_runner.ScriptInfo
	(*ListScriptsResponse)(nil),         // 24: zeek_runner.ListScriptsResponse
	(*GetScriptRequest)(nil),            // 25: zeek_runner.GetScriptRequest
	(*ReloadScriptsRequest)(nil),        // 26: zeek_runner.ReloadScriptsRequest
	(*ReloadScriptsResponse)(nil),       // 27: zeek_runner.ReloadScriptsResponse
	(*ApplyBehaviorPolicyRequest)(nil),  // 28: zeek_runner.ApplyBehaviorPolicyRequest
	(*ApplyBehaviorPolicyResponse)(nil), // 29: zeek_runner.ApplyBehaviorPolicyResponse
	(*GetTaskHitsRequest)(nil),          // 30: zeek_runner.GetTaskHitsRequest
	(*HitEvent)(nil),                    // 31: zeek_runner.HitEvent
	(*GetTaskHitsResponse)(nil),         // 32: zeek_runner.GetTaskHitsResponse
}
var file_api_pb_zeek_runner_proto_depIdxs = []int32{
	12, // 0: zeek_runner.AsyncAnalyzeBatchRequest.scripts:type_name -> zeek_runner.ScriptTask
	20, // 1: zeek_runner.ParentTaskStatusResponse.subTasks:type_name -> zeek_runner.SubTaskSummary
	23, // 2: zeek_runner.ListScriptsResponse.scripts:type_name -> zeek_runner.ScriptInfo
	23, // 3: zeek_runner.ReloadScriptsResponse.scripts:type_name -> zeek_runner.ScriptInfo
	31, // 4: zeek_runner.GetTaskHitsResponse.hits:type_name -> zeek_runner.HitEvent
	0,  // 5: zeek_runner.ZeekAnalysisService.Analyze:input_type -> zeek_runner.AnalyzeRequest
	10, // 6: zeek_runner.ZeekAnalysisService.AsyncAnalyze:input_type -> zeek_runner.AsyncAnalyzeRequest
	13, // 7: zeek_runner.ZeekAnalysisService.AsyncAnalyzeBatch:input_type -> zeek_runner.AsyncAnalyzeBatchRequest
	2,  // 8: zeek_runner.ZeekAnalysisService.Extract:input_type -> zeek_runner.ExtractRequest
	15, // 9: zeek_runner.ZeekAnalysisService.ExtractAsync:input_type -> zeek_runner.ExtractAsyncRequest
	17, // 10: zeek_runner.ZeekAnalysisService.GetTaskStatus:input_type -> zeek_runner.TaskStatusRequest
	19, // 11: zeek_runner.ZeekAnalysisService.GetParentTaskStatus:input_type -> zeek_runner.ParentTaskStatusRequest
	4,  // 12: zeek_runner.ZeekAnalysisService.CapacityCheck:input_type -> zeek_runner.CapacityCheckRequest
	6,  // 13: zeek_runner.ZeekAnalysisService.VersionCheck:input_type -> zeek_runner.VersionCheckRequest
	8,  // 14: zeek_runner.ZeekAnalysisService.ZeekSyntaxCheck:input_type -> zeek_runner.ZeekSyntaxCheckRequest
	22, // 15: zeek_runner.ZeekAnalysisService.ListScripts:input_type -> zeek_runner.ListScriptsRequest
	25, // 16: zeek_runner.ZeekAnalysisService.GetScript:input_type -> zeek_runner.GetScriptRequest
	26, // 17: zeek_runner.ZeekAnalysisService.ReloadScripts:input_type -> zeek_runner.ReloadScriptsRequest
	28, // 18: zeek_runner.ZeekAnalysisService.ApplyBehaviorPolicy:input_type -> zeek_runner.ApplyBehaviorPolicyRequest
	30, // 19: zeek_runner.ZeekAnalysisService.GetTaskHits:input_type -> zeek_runner.GetTaskHitsRequest
	1,  // 20: zeek_runner.ZeekAnalysisService.Analyze:output_type -> zeek_runner.AnalyzeResponse
	11, // 21: zeek_runner.ZeekAnalysisService.AsyncAnalyze:output_type -> zeek_runner.AsyncAnalyzeResponse
	14, // 22: zeek_runner.ZeekAnalysisService.AsyncAnalyzeBatch:output_type -> zeek_runner.AsyncAnalyzeBatchResponse
	3,  // 23: zeek_runner.ZeekAnalysisService.Extract:output_type -> zeek_runner.ExtractResponse
	16, // 24: zeek_runner.ZeekAnalysisService.ExtractAsync:output_type -> zeek_runner.ExtractAsyncResponse
	18, // 25: zeek_runner.ZeekAnalysisService.GetTaskStatus:output_type -> zeek_runner.TaskStatusResponse
	21, // 26: zeek_runner.ZeekAnalysisService.GetParentTaskStatus:output_type -> zeek_runner.ParentTaskStatusResponse
	5,  // 27: zeek_runner.ZeekAnalysisService.CapacityCheck:output_type -> zeek_runner.CapacityCheckResponse
	7,  // 28: zeek_runner.ZeekAnalysisService.VersionCheck:output_type -> zeek_runner.VersionCheckResponse
	9,  // 29: zeek_runner.ZeekAnalysisService.ZeekSyntaxCheck:output_type -> zeek_runner.ZeekSyntaxCheckResponse
	24, // 30: zeek_runner.ZeekAnalysisService.ListScripts:output_type -> zeek_runner.ListScriptsResponse
	23, // 31: zeek_runner.ZeekAnalysisService.GetScript:output_type -> zeek_runner.ScriptInfo
	27, // 32: zeek_runner.ZeekAnalysisService.ReloadScripts:output_type -> zeek_runner.ReloadScriptsResponse
	29, // 33: zeek_runner.ZeekAnalysisService.ApplyBehaviorPolicy:output_type -> zeek_runner.ApplyBehaviorPolicyResponse
	32, // 34: zeek_runner.ZeekAnalysisService.GetTaskHits:output_type -> zeek_runner.GetTaskHitsResponse
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_pb_zeek_runner_proto_init() }
func file_api_pb_zeek_runner_proto_init() {
	if File_api_pb_zeek_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_zeek_runner_proto_rawDesc), len(file_api_pb_zeek_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_zeek_runner_proto_goTypes,
		DependencyIndexes: file_api_pb_zeek_runner_proto_depIdxs,
		MessageInfos:      file_api_pb_zeek_runner_proto_msgTypes,
	}.Build()
	File_api_pb_zeek_runner_proto = out.File
	file_api_pb_zeek_runner_proto_goTypes = nil
	file_api_pb_zeek_runner_proto_depIdxs = nil
}
