// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/pb/zeek_runner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求体
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`          // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`              // UUID
	OnlyNotice    bool                   `protobuf:"varint,3,opt,name=onlyNotice,proto3" json:"onlyNotice,omitempty"` // 是否只生成notice日志
	PcapID        string                 `protobuf:"bytes,4,opt,name=pcapID,proto3" json:"pcapID,omitempty"`          // pcap文件ID
	PcapPath      string                 `protobuf:"bytes,5,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`      // pcap文件路径
	ScriptID      string                 `protobuf:"bytes,6,opt,name=scriptID,proto3" json:"scriptID,omitempty"`      // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,7,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`  // 脚本路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AnalyzeRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AnalyzeRequest) GetOnlyNotice() bool {
	if x != nil {
		return x.OnlyNotice
	}
	return false
}

func (x *AnalyzeRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *AnalyzeRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AnalyzeRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *AnalyzeRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

// 响应体
type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	PcapPath      string                 `protobuf:"bytes,3,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`     // pcap文件路径
	ScriptPath    string                 `protobuf:"bytes,4,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"` // 脚本路径
	StartTime     string                 `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`   // 任务开始时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AnalyzeResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AnalyzeResponse) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AnalyzeResponse) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *AnalyzeResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

// 文件提取请求
type ExtractRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskID               string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`                              // 任务ID
	Uuid                 string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                                  // UUID
	PcapID               string                 `protobuf:"bytes,3,opt,name=pcapID,proto3" json:"pcapID,omitempty"`                              // pcap文件ID
	PcapPath             string                 `protobuf:"bytes,4,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`                          // pcap文件路径
	ScriptPath           string                 `protobuf:"bytes,5,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`                      // 脚本路径（可选，绝对路径）
	OutputDir            string                 `protobuf:"bytes,6,opt,name=outputDir,proto3" json:"outputDir,omitempty"`                        // 提取文件存储路径
	ExtractedFileMinSize int32                  `protobuf:"varint,7,opt,name=extractedFileMinSize,proto3" json:"extractedFileMinSize,omitempty"` // 提取文件最小大小(KB)
	ExtractedFileMaxSize int32                  `protobuf:"varint,8,opt,name=extractedFileMaxSize,proto3" json:"extractedFileMaxSize,omitempty"` // 提取文件最大大小(MB)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExtractRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExtractRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *ExtractRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *ExtractRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ExtractRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ExtractRequest) GetExtractedFileMinSize() int32 {
	if x != nil {
		return x.ExtractedFileMinSize
	}
	return 0
}

func (x *ExtractRequest) GetExtractedFileMaxSize() int32 {
	if x != nil {
		return x.ExtractedFileMaxSize
	}
	return 0
}

// 文件提取响应
type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	PcapPath      string                 `protobuf:"bytes,3,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`     // pcap文件路径
	ScriptPath    string                 `protobuf:"bytes,4,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"` // 脚本路径
	OutputDir     string                 `protobuf:"bytes,5,opt,name=outputDir,proto3" json:"outputDir,omitempty"`   // 提取文件存储路径
	StartTime     string                 `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`   // 任务开始时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExtractResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExtractResponse) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *ExtractResponse) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ExtractResponse) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ExtractResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{4}
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PoolRunning   int32                  `protobuf:"varint,2,opt,name=pool_running,json=poolRunning,proto3" json:"pool_running,omitempty"`
	PoolCapacity  int32                  `protobuf:"varint,3,opt,name=pool_capacity,json=poolCapacity,proto3" json:"pool_capacity,omitempty"`
	KafkaReady    bool                   `protobuf:"varint,4,opt,name=kafka_ready,json=kafkaReady,proto3" json:"kafka_ready,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	GoVersion     string                 `protobuf:"bytes,7,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	Os            string                 `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,9,opt,name=arch,proto3" json:"arch,omitempty"`
	RedisReady    bool                   `protobuf:"varint,10,opt,name=redis_ready,json=redisReady,proto3" json:"redis_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetPoolRunning() int32 {
	if x != nil {
		return x.PoolRunning
	}
	return 0
}

func (x *HealthCheckResponse) GetPoolCapacity() int32 {
	if x != nil {
		return x.PoolCapacity
	}
	return 0
}

func (x *HealthCheckResponse) GetKafkaReady() bool {
	if x != nil {
		return x.KafkaReady
	}
	return false
}

func (x *HealthCheckResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *HealthCheckResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HealthCheckResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HealthCheckResponse) GetRedisReady() bool {
	if x != nil {
		return x.RedisReady
	}
	return false
}

// 版本检查请求
type VersionCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // 组件名称 (zeek 或 zeek-kafka)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionCheckRequest) Reset() {
	*x = VersionCheckRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionCheckRequest) ProtoMessage() {}

func (x *VersionCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionCheckRequest.ProtoReflect.Descriptor instead.
func (*VersionCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{6}
}

func (x *VersionCheckRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

// 版本检查响应
type VersionCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // 组件名称
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`     // 版本信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionCheckResponse) Reset() {
	*x = VersionCheckResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionCheckResponse) ProtoMessage() {}

func (x *VersionCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionCheckResponse.ProtoReflect.Descriptor instead.
func (*VersionCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{7}
}

func (x *VersionCheckResponse) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *VersionCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ZeekSyntaxCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptID      string                 `protobuf:"bytes,1,opt,name=scriptID,proto3" json:"scriptID,omitempty"`           // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,2,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`       // 脚本路径
	ScriptContent string                 `protobuf:"bytes,3,opt,name=scriptContent,proto3" json:"scriptContent,omitempty"` // 脚本内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeekSyntaxCheckRequest) Reset() {
	*x = ZeekSyntaxCheckRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeekSyntaxCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeekSyntaxCheckRequest) ProtoMessage() {}

func (x *ZeekSyntaxCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeekSyntaxCheckRequest.ProtoReflect.Descriptor instead.
func (*ZeekSyntaxCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{8}
}

func (x *ZeekSyntaxCheckRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *ZeekSyntaxCheckRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ZeekSyntaxCheckRequest) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

type ZeekSyntaxCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"` // 是否有效
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`  // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeekSyntaxCheckResponse) Reset() {
	*x = ZeekSyntaxCheckResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeekSyntaxCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeekSyntaxCheckResponse) ProtoMessage() {}

func (x *ZeekSyntaxCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeekSyntaxCheckResponse.ProtoReflect.Descriptor instead.
func (*ZeekSyntaxCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{9}
}

func (x *ZeekSyntaxCheckResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ZeekSyntaxCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AsyncAnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`          // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`              // UUID
	OnlyNotice    bool                   `protobuf:"varint,3,opt,name=onlyNotice,proto3" json:"onlyNotice,omitempty"` // 是否只生成notice日志
	PcapID        string                 `protobuf:"bytes,4,opt,name=pcapID,proto3" json:"pcapID,omitempty"`          // pcap文件ID
	PcapPath      string                 `protobuf:"bytes,5,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`      // pcap文件路径
	ScriptID      string                 `protobuf:"bytes,6,opt,name=scriptID,proto3" json:"scriptID,omitempty"`      // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,7,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`  // 脚本路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncAnalyzeRequest) Reset() {
	*x = AsyncAnalyzeRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncAnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncAnalyzeRequest) ProtoMessage() {}

func (x *AsyncAnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncAnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AsyncAnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{10}
}

func (x *AsyncAnalyzeRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetOnlyNotice() bool {
	if x != nil {
		return x.OnlyNotice
	}
	return false
}

func (x *AsyncAnalyzeRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *AsyncAnalyzeRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

// 异步分析响应
type AsyncAnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`         // 任务状态
	CreateTime    string                 `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncAnalyzeResponse) Reset() {
	*x = AsyncAnalyzeResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncAnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncAnalyzeResponse) ProtoMessage() {}

func (x *AsyncAnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncAnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AsyncAnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{11}
}

func (x *AsyncAnalyzeResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AsyncAnalyzeResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AsyncAnalyzeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AsyncAnalyzeResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 异步文件提取请求
type ExtractAsyncRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskID               string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`                              // 任务ID
	Uuid                 string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                                  // UUID
	PcapID               string                 `protobuf:"bytes,3,opt,name=pcapID,proto3" json:"pcapID,omitempty"`                              // pcap文件ID
	PcapPath             string                 `protobuf:"bytes,4,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`                          // pcap文件路径
	ScriptPath           string                 `protobuf:"bytes,5,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`                      // 脚本路径（可选，绝对路径）
	OutputDir            string                 `protobuf:"bytes,6,opt,name=outputDir,proto3" json:"outputDir,omitempty"`                        // 提取文件存储路径
	ExtractedFileMinSize int32                  `protobuf:"varint,7,opt,name=extractedFileMinSize,proto3" json:"extractedFileMinSize,omitempty"` // 提取文件最小大小(KB)
	ExtractedFileMaxSize int32                  `protobuf:"varint,8,opt,name=extractedFileMaxSize,proto3" json:"extractedFileMaxSize,omitempty"` // 提取文件最大大小(MB)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExtractAsyncRequest) Reset() {
	*x = ExtractAsyncRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractAsyncRequest) ProtoMessage() {}

func (x *ExtractAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractAsyncRequest.ProtoReflect.Descriptor instead.
func (*ExtractAsyncRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{12}
}

func (x *ExtractAsyncRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExtractAsyncRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExtractAsyncRequest) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *ExtractAsyncRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *ExtractAsyncRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ExtractAsyncRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ExtractAsyncRequest) GetExtractedFileMinSize() int32 {
	if x != nil {
		return x.ExtractedFileMinSize
	}
	return 0
}

func (x *ExtractAsyncRequest) GetExtractedFileMaxSize() int32 {
	if x != nil {
		return x.ExtractedFileMaxSize
	}
	return 0
}

// 异步文件提取响应
type ExtractAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`         // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`             // UUID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`         // 任务状态
	CreateTime    string                 `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractAsyncResponse) Reset() {
	*x = ExtractAsyncResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractAsyncResponse) ProtoMessage() {}

func (x *ExtractAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractAsyncResponse.ProtoReflect.Descriptor instead.
func (*ExtractAsyncResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{13}
}

func (x *ExtractAsyncResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExtractAsyncResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExtractAsyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExtractAsyncResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 任务状态查询请求
type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 子任务UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{14}
}

func (x *TaskStatusRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 任务状态查询响应
type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`             // 任务ID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                 // UUID
	PcapID        string                 `protobuf:"bytes,3,opt,name=pcapID,proto3" json:"pcapID,omitempty"`             // pcap文件ID
	PcapPath      string                 `protobuf:"bytes,4,opt,name=pcapPath,proto3" json:"pcapPath,omitempty"`         // pcap文件路径
	ScriptID      string                 `protobuf:"bytes,5,opt,name=scriptID,proto3" json:"scriptID,omitempty"`         // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,6,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`     // 脚本路径
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`             // 任务状态
	CreateTime    string                 `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`     // 创建时间
	StartTime     string                 `protobuf:"bytes,9,opt,name=startTime,proto3" json:"startTime,omitempty"`       // 开始时间
	EndTime       string                 `protobuf:"bytes,10,opt,name=endTime,proto3" json:"endTime,omitempty"`          // 结束时间
	Duration      float64                `protobuf:"fixed64,11,opt,name=duration,proto3" json:"duration,omitempty"`      // 执行时长(秒)
	HitCount      int32                  `protobuf:"varint,12,opt,name=hitCount,proto3" json:"hitCount,omitempty"`       // 命中总数
	NoticeCount   int32                  `protobuf:"varint,13,opt,name=noticeCount,proto3" json:"noticeCount,omitempty"` // notice日志数
	IntelCount    int32                  `protobuf:"varint,14,opt,name=intelCount,proto3" json:"intelCount,omitempty"`   // intel日志数
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`              // 错误信息
	Output        string                 `protobuf:"bytes,16,opt,name=output,proto3" json:"output,omitempty"`            // 输出内容
	Retries       int32                  `protobuf:"varint,17,opt,name=retries,proto3" json:"retries,omitempty"`         // 重试次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{15}
}

func (x *TaskStatusResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskStatusResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TaskStatusResponse) GetPcapID() string {
	if x != nil {
		return x.PcapID
	}
	return ""
}

func (x *TaskStatusResponse) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *TaskStatusResponse) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *TaskStatusResponse) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *TaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatusResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *TaskStatusResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TaskStatusResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TaskStatusResponse) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TaskStatusResponse) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *TaskStatusResponse) GetNoticeCount() int32 {
	if x != nil {
		return x.NoticeCount
	}
	return 0
}

func (x *TaskStatusResponse) GetIntelCount() int32 {
	if x != nil {
		return x.IntelCount
	}
	return 0
}

func (x *TaskStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskStatusResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskStatusResponse) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

// 父任务状态查询请求
type ParentTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"` // 父任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentTaskStatusRequest) Reset() {
	*x = ParentTaskStatusRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentTaskStatusRequest) ProtoMessage() {}

func (x *ParentTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*ParentTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{16}
}

func (x *ParentTaskStatusRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

// 子任务摘要
type SubTaskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                // 子任务UUID
	ScriptID      string                 `protobuf:"bytes,2,opt,name=scriptID,proto3" json:"scriptID,omitempty"`        // 脚本ID
	ScriptPath    string                 `protobuf:"bytes,3,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`    // 脚本路径
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`            // 状态
	Duration      float64                `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`      // 执行时长(秒)
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`              // 错误信息
	HitCount      int32                  `protobuf:"varint,7,opt,name=hitCount,proto3" json:"hitCount,omitempty"`       // 命中总数
	NoticeCount   int32                  `protobuf:"varint,8,opt,name=noticeCount,proto3" json:"noticeCount,omitempty"` // notice日志数
	IntelCount    int32                  `protobuf:"varint,9,opt,name=intelCount,proto3" json:"intelCount,omitempty"`   // intel日志数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubTaskSummary) Reset() {
	*x = SubTaskSummary{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubTaskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTaskSummary) ProtoMessage() {}

func (x *SubTaskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubTaskSummary.ProtoReflect.Descriptor instead.
func (*SubTaskSummary) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{17}
}

func (x *SubTaskSummary) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SubTaskSummary) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *SubTaskSummary) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *SubTaskSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubTaskSummary) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SubTaskSummary) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SubTaskSummary) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *SubTaskSummary) GetNoticeCount() int32 {
	if x != nil {
		return x.NoticeCount
	}
	return 0
}

func (x *SubTaskSummary) GetIntelCount() int32 {
	if x != nil {
		return x.IntelCount
	}
	return 0
}

// 父任务状态查询响应
type ParentTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`              // 父任务ID
	TotalCount    int32                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`     // 总子任务数
	PendingCount  int32                  `protobuf:"varint,3,opt,name=pendingCount,proto3" json:"pendingCount,omitempty"` // 待处理数
	RunningCount  int32                  `protobuf:"varint,4,opt,name=runningCount,proto3" json:"runningCount,omitempty"` // 运行中数
	SuccessCount  int32                  `protobuf:"varint,5,opt,name=successCount,proto3" json:"successCount,omitempty"` // 成功数
	FailedCount   int32                  `protobuf:"varint,6,opt,name=failedCount,proto3" json:"failedCount,omitempty"`   // 失败数
	TimeoutCount  int32                  `protobuf:"varint,7,opt,name=timeoutCount,proto3" json:"timeoutCount,omitempty"` // 超时数
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`              // 聚合状态: pending/running/completed/partial_failed/failed
	SubTasks      []*SubTaskSummary      `protobuf:"bytes,9,rep,name=subTasks,proto3" json:"subTasks,omitempty"`          // 子任务列表
	HitCount      int32                  `protobuf:"varint,10,opt,name=hitCount,proto3" json:"hitCount,omitempty"`        // 所有子任务命中总数
	NoticeCount   int32                  `protobuf:"varint,11,opt,name=noticeCount,proto3" json:"noticeCount,omitempty"`  // 所有子任务notice日志总数
	IntelCount    int32                  `protobuf:"varint,12,opt,name=intelCount,proto3" json:"intelCount,omitempty"`    // 所有子任务intel日志总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentTaskStatusResponse) Reset() {
	*x = ParentTaskStatusResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentTaskStatusResponse) ProtoMessage() {}

func (x *ParentTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*ParentTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{18}
}

func (x *ParentTaskStatusResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ParentTaskStatusResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetPendingCount() int32 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetRunningCount() int32 {
	if x != nil {
		return x.RunningCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetTimeoutCount() int32 {
	if x != nil {
		return x.TimeoutCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ParentTaskStatusResponse) GetSubTasks() []*SubTaskSummary {
	if x != nil {
		return x.SubTasks
	}
	return nil
}

func (x *ParentTaskStatusResponse) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetNoticeCount() int32 {
	if x != nil {
		return x.NoticeCount
	}
	return 0
}

func (x *ParentTaskStatusResponse) GetIntelCount() int32 {
	if x != nil {
		return x.IntelCount
	}
	return 0
}

type ListScriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnabledOnly   bool                   `protobuf:"varint,2,opt,name=enabledOnly,proto3" json:"enabledOnly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsRequest) Reset() {
	*x = ListScriptsRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsRequest) ProtoMessage() {}

func (x *ListScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsRequest.ProtoReflect.Descriptor instead.
func (*ListScriptsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{19}
}

func (x *ListScriptsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListScriptsRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ScriptInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScriptID         string                 `protobuf:"bytes,1,opt,name=scriptID,proto3" json:"scriptID,omitempty"`
	ScriptName       string                 `protobuf:"bytes,2,opt,name=scriptName,proto3" json:"scriptName,omitempty"`
	ScriptPath       string                 `protobuf:"bytes,3,opt,name=scriptPath,proto3" json:"scriptPath,omitempty"`
	ExpCodeType      string                 `protobuf:"bytes,4,opt,name=expCodeType,proto3" json:"expCodeType,omitempty"`
	Size             string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	BehaviorType     string                 `protobuf:"bytes,6,opt,name=behaviorType,proto3" json:"behaviorType,omitempty"`
	BehaviorCategory string                 `protobuf:"bytes,7,opt,name=behaviorCategory,proto3" json:"behaviorCategory,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	AttackFeature    string                 `protobuf:"bytes,9,opt,name=attackFeature,proto3" json:"attackFeature,omitempty"`
	Checksum         string                 `protobuf:"bytes,10,opt,name=checksum,proto3" json:"checksum,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Enabled          bool                   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Valid            bool                   `protobuf:"varint,13,opt,name=valid,proto3" json:"valid,omitempty"`
	Error            string                 `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScriptInfo) Reset() {
	*x = ScriptInfo{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptInfo) ProtoMessage() {}

func (x *ScriptInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptInfo.ProtoReflect.Descriptor instead.
func (*ScriptInfo) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{20}
}

func (x *ScriptInfo) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

func (x *ScriptInfo) GetScriptName() string {
	if x != nil {
		return x.ScriptName
	}
	return ""
}

func (x *ScriptInfo) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ScriptInfo) GetExpCodeType() string {
	if x != nil {
		return x.ExpCodeType
	}
	return ""
}

func (x *ScriptInfo) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ScriptInfo) GetBehaviorType() string {
	if x != nil {
		return x.BehaviorType
	}
	return ""
}

func (x *ScriptInfo) GetBehaviorCategory() string {
	if x != nil {
		return x.BehaviorCategory
	}
	return ""
}

func (x *ScriptInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScriptInfo) GetAttackFeature() string {
	if x != nil {
		return x.AttackFeature
	}
	return ""
}

func (x *ScriptInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ScriptInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ScriptInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScriptInfo) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ScriptInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListScriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scripts       []*ScriptInfo          `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsResponse) Reset() {
	*x = ListScriptsResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsResponse) ProtoMessage() {}

func (x *ListScriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsResponse.ProtoReflect.Descriptor instead.
func (*ListScriptsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{21}
}

func (x *ListScriptsResponse) GetScripts() []*ScriptInfo {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type GetScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptID      string                 `protobuf:"bytes,1,opt,name=scriptID,proto3" json:"scriptID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScriptRequest) Reset() {
	*x = GetScriptRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScriptRequest) ProtoMessage() {}

func (x *GetScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScriptRequest.ProtoReflect.Descriptor instead.
func (*GetScriptRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{22}
}

func (x *GetScriptRequest) GetScriptID() string {
	if x != nil {
		return x.ScriptID
	}
	return ""
}

type ReloadScriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadScriptsRequest) Reset() {
	*x = ReloadScriptsRequest{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadScriptsRequest) ProtoMessage() {}

func (x *ReloadScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadScriptsRequest.ProtoReflect.Descriptor instead.
func (*ReloadScriptsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{23}
}

type ReloadScriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Valid         int32                  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Invalid       int32                  `protobuf:"varint,3,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Scripts       []*ScriptInfo          `protobuf:"bytes,4,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadScriptsResponse) Reset() {
	*x = ReloadScriptsResponse{}
	mi := &file_api_pb_zeek_runner_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadScriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadScriptsResponse) ProtoMessage() {}

func (x *ReloadScriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_zeek_runner_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadScriptsResponse.ProtoReflect.Descriptor instead.
func (*ReloadScriptsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_zeek_runner_proto_rawDescGZIP(), []int{24}
}

func (x *ReloadScriptsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ReloadScriptsResponse) GetValid() int32 {
	if x != nil {
		return x.Valid
	}
	return 0
}

func (x *ReloadScriptsResponse) GetInvalid() int32 {
	if x != nil {
		return x.Invalid
	}
	return 0
}

func (x *ReloadScriptsResponse) GetScripts() []*ScriptInfo {
	if x != nil {
		return x.Scripts
	}
	return nil
}

var File_api_pb_zeek_runner_proto protoreflect.FileDescriptor

const file_api_pb_zeek_runner_proto_rawDesc = "" +
	"\n" +
	"\x18api/pb/zeek_runner.proto\x12\vzeek_runner\"\xcc\x01\n" +
	"\x0eAnalyzeRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"onlyNotice\x18\x03 \x01(\bR\n" +
	"onlyNotice\x12\x16\n" +
	"\x06pcapID\x18\x04 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x05 \x01(\tR\bpcapPath\x12\x1a\n" +
	"\bscriptID\x18\x06 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\a \x01(\tR\n" +
	"scriptPath\"\x97\x01\n" +
	"\x0fAnalyzeResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpcapPath\x18\x03 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x04 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\"\x96\x02\n" +
	"\x0eExtractRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06pcapID\x18\x03 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x04 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x05 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\toutputDir\x18\x06 \x01(\tR\toutputDir\x122\n" +
	"\x14extractedFileMinSize\x18\a \x01(\x05R\x14extractedFileMinSize\x122\n" +
	"\x14extractedFileMaxSize\x18\b \x01(\x05R\x14extractedFileMaxSize\"\xb5\x01\n" +
	"\x0fExtractResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpcapPath\x18\x03 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x04 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\toutputDir\x18\x05 \x01(\tR\toutputDir\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\tR\tstartTime\"\x14\n" +
	"\x12HealthCheckRequest\"\xb2\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fpool_running\x18\x02 \x01(\x05R\vpoolRunning\x12#\n" +
	"\rpool_capacity\x18\x03 \x01(\x05R\fpoolCapacity\x12\x1f\n" +
	"\vkafka_ready\x18\x04 \x01(\bR\n" +
	"kafkaReady\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"go_version\x18\a \x01(\tR\tgoVersion\x12\x0e\n" +
	"\x02os\x18\b \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\t \x01(\tR\x04arch\x12\x1f\n" +
	"\vredis_ready\x18\n" +
	" \x01(\bR\n" +
	"redisReady\"3\n" +
	"\x13VersionCheckRequest\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\"N\n" +
	"\x14VersionCheckResponse\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"z\n" +
	"\x16ZeekSyntaxCheckRequest\x12\x1a\n" +
	"\bscriptID\x18\x01 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x02 \x01(\tR\n" +
	"scriptPath\x12$\n" +
	"\rscriptContent\x18\x03 \x01(\tR\rscriptContent\"E\n" +
	"\x17ZeekSyntaxCheckResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd1\x01\n" +
	"\x13AsyncAnalyzeRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"onlyNotice\x18\x03 \x01(\bR\n" +
	"onlyNotice\x12\x16\n" +
	"\x06pcapID\x18\x04 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x05 \x01(\tR\bpcapPath\x12\x1a\n" +
	"\bscriptID\x18\x06 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\a \x01(\tR\n" +
	"scriptPath\"z\n" +
	"\x14AsyncAnalyzeResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\tR\n" +
	"createTime\"\x9b\x02\n" +
	"\x13ExtractAsyncRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06pcapID\x18\x03 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x04 \x01(\tR\bpcapPath\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x05 \x01(\tR\n" +
	"scriptPath\x12\x1c\n" +
	"\toutputDir\x18\x06 \x01(\tR\toutputDir\x122\n" +
	"\x14extractedFileMinSize\x18\a \x01(\x05R\x14extractedFileMinSize\x122\n" +
	"\x14extractedFileMaxSize\x18\b \x01(\x05R\x14extractedFileMaxSize\"z\n" +
	"\x14ExtractAsyncResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\tR\n" +
	"createTime\"'\n" +
	"\x11TaskStatusRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xe2\x03\n" +
	"\x12TaskStatusResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06pcapID\x18\x03 \x01(\tR\x06pcapID\x12\x1a\n" +
	"\bpcapPath\x18\x04 \x01(\tR\bpcapPath\x12\x1a\n" +
	"\bscriptID\x18\x05 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x06 \x01(\tR\n" +
	"scriptPath\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\tR\n" +
	"createTime\x12\x1c\n" +
	"\tstartTime\x18\t \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\n" +
	" \x01(\tR\aendTime\x12\x1a\n" +
	"\bduration\x18\v \x01(\x01R\bduration\x12\x1a\n" +
	"\bhitCount\x18\f \x01(\x05R\bhitCount\x12 \n" +
	"\vnoticeCount\x18\r \x01(\x05R\vnoticeCount\x12\x1e\n" +
	"\n" +
	"intelCount\x18\x0e \x01(\x05R\n" +
	"intelCount\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x10 \x01(\tR\x06output\x12\x18\n" +
	"\aretries\x18\x11 \x01(\x05R\aretries\"1\n" +
	"\x17ParentTaskStatusRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\"\x88\x02\n" +
	"\x0eSubTaskSummary\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bscriptID\x18\x02 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x03 \x01(\tR\n" +
	"scriptPath\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x01R\bduration\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1a\n" +
	"\bhitCount\x18\a \x01(\x05R\bhitCount\x12 \n" +
	"\vnoticeCount\x18\b \x01(\x05R\vnoticeCount\x12\x1e\n" +
	"\n" +
	"intelCount\x18\t \x01(\x05R\n" +
	"intelCount\"\xb3\x03\n" +
	"\x18ParentTaskStatusResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\"\n" +
	"\fpendingCount\x18\x03 \x01(\x05R\fpendingCount\x12\"\n" +
	"\frunningCount\x18\x04 \x01(\x05R\frunningCount\x12\"\n" +
	"\fsuccessCount\x18\x05 \x01(\x05R\fsuccessCount\x12 \n" +
	"\vfailedCount\x18\x06 \x01(\x05R\vfailedCount\x12\"\n" +
	"\ftimeoutCount\x18\a \x01(\x05R\ftimeoutCount\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x127\n" +
	"\bsubTasks\x18\t \x03(\v2\x1b.zeek_runner.SubTaskSummaryR\bsubTasks\x12\x1a\n" +
	"\bhitCount\x18\n" +
	" \x01(\x05R\bhitCount\x12 \n" +
	"\vnoticeCount\x18\v \x01(\x05R\vnoticeCount\x12\x1e\n" +
	"\n" +
	"intelCount\x18\f \x01(\x05R\n" +
	"intelCount\"J\n" +
	"\x12ListScriptsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\venabledOnly\x18\x02 \x01(\bR\venabledOnly\"\xb6\x03\n" +
	"\n" +
	"ScriptInfo\x12\x1a\n" +
	"\bscriptID\x18\x01 \x01(\tR\bscriptID\x12\x1e\n" +
	"\n" +
	"scriptName\x18\x02 \x01(\tR\n" +
	"scriptName\x12\x1e\n" +
	"\n" +
	"scriptPath\x18\x03 \x01(\tR\n" +
	"scriptPath\x12 \n" +
	"\vexpCodeType\x18\x04 \x01(\tR\vexpCodeType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12\"\n" +
	"\fbehaviorType\x18\x06 \x01(\tR\fbehaviorType\x12*\n" +
	"\x10behaviorCategory\x18\a \x01(\tR\x10behaviorCategory\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12$\n" +
	"\rattackFeature\x18\t \x01(\tR\rattackFeature\x12\x1a\n" +
	"\bchecksum\x18\n" +
	" \x01(\tR\bchecksum\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aenabled\x18\f \x01(\bR\aenabled\x12\x14\n" +
	"\x05valid\x18\r \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x0e \x01(\tR\x05error\"H\n" +
	"\x13ListScriptsResponse\x121\n" +
	"\ascripts\x18\x01 \x03(\v2\x17.zeek_runner.ScriptInfoR\ascripts\".\n" +
	"\x10GetScriptRequest\x12\x1a\n" +
	"\bscriptID\x18\x01 \x01(\tR\bscriptID\"\x16\n" +
	"\x14ReloadScriptsRequest\"\x90\x01\n" +
	"\x15ReloadScriptsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\x05R\x05valid\x12\x18\n" +
	"\ainvalid\x18\x03 \x01(\x05R\ainvalid\x121\n" +
	"\ascripts\x18\x04 \x03(\v2\x17.zeek_runner.ScriptInfoR\ascripts2\x8d\b\n" +
	"\x13ZeekAnalysisService\x12F\n" +
	"\aAnalyze\x12\x1b.zeek_runner.AnalyzeRequest\x1a\x1c.zeek_runner.AnalyzeResponse\"\x00\x12U\n" +
	"\fAsyncAnalyze\x12 .zeek_runner.AsyncAnalyzeRequest\x1a!.zeek_runner.AsyncAnalyzeResponse\"\x00\x12F\n" +
	"\aExtract\x12\x1b.zeek_runner.ExtractRequest\x1a\x1c.zeek_runner.ExtractResponse\"\x00\x12U\n" +
	"\fExtractAsync\x12 .zeek_runner.ExtractAsyncRequest\x1a!.zeek_runner.ExtractAsyncResponse\"\x00\x12R\n" +
	"\rGetTaskStatus\x12\x1e.zeek_runner.TaskStatusRequest\x1a\x1f.zeek_runner.TaskStatusResponse\"\x00\x12d\n" +
	"\x13GetParentTaskStatus\x12$.zeek_runner.ParentTaskStatusRequest\x1a%.zeek_runner.ParentTaskStatusResponse\"\x00\x12R\n" +
	"\vHealthCheck\x12\x1f.zeek_runner.HealthCheckRequest\x1a .zeek_runner.HealthCheckResponse\"\x00\x12U\n" +
	"\fVersionCheck\x12 .zeek_runner.VersionCheckRequest\x1a!.zeek_runner.VersionCheckResponse\"\x00\x12^\n" +
	"\x0fZeekSyntaxCheck\x12#.zeek_runner.ZeekSyntaxCheckRequest\x1a$.zeek_runner.ZeekSyntaxCheckResponse\"\x00\x12R\n" +
	"\vListScripts\x12\x1f.zeek_runner.ListScriptsRequest\x1a .zeek_runner.ListScriptsResponse\"\x00\x12E\n" +
	"\tGetScript\x12\x1d.zeek_runner.GetScriptRequest\x1a\x17.zeek_runner.ScriptInfo\"\x00\x12X\n" +
	"\rReloadScripts\x12!.zeek_runner.ReloadScriptsRequest\x1a\".zeek_runner.ReloadScriptsResponse\"\x00B\x14Z\x12zeek_runner/api/pbb\x06proto3"

var (
	file_api_pb_zeek_runner_proto_rawDescOnce sync.Once
	file_api_pb_zeek_runner_proto_rawDescData []byte
)

func file_api_pb_zeek_runner_proto_rawDescGZIP() []byte {
	file_api_pb_zeek_runner_proto_rawDescOnce.Do(func() {
		file_api_pb_zeek_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_zeek_runner_proto_rawDesc), len(file_api_pb_zeek_runner_proto_rawDesc)))
	})
	return file_api_pb_zeek_runner_proto_rawDescData
}

var file_api_pb_zeek_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_pb_zeek_runner_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),           // 0: zeek_runner.AnalyzeRequest
	(*AnalyzeResponse)(nil),          // 1: zeek_runner.AnalyzeResponse
	(*ExtractRequest)(nil),           // 2: zeek_runner.ExtractRequest
	(*ExtractResponse)(nil),          // 3: zeek_runner.ExtractResponse
	(*HealthCheckRequest)(nil),       // 4: zeek_runner.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 5: zeek_runner.HealthCheckResponse
	(*VersionCheckRequest)(nil),      // 6: zeek_runner.VersionCheckRequest
	(*VersionCheckResponse)(nil),     // 7: zeek_runner.VersionCheckResponse
	(*ZeekSyntaxCheckRequest)(nil),   // 8: zeek_runner.ZeekSyntaxCheckRequest
	(*ZeekSyntaxCheckResponse)(nil),  // 9: zeek_runner.ZeekSyntaxCheckResponse
	(*AsyncAnalyzeRequest)(nil),      // 10: zeek_runner.AsyncAnalyzeRequest
	(*AsyncAnalyzeResponse)(nil),     // 11: zeek_runner.AsyncAnalyzeResponse
	(*ExtractAsyncRequest)(nil),      // 12: zeek_runner.ExtractAsyncRequest
	(*ExtractAsyncResponse)(nil),     // 13: zeek_runner.ExtractAsyncResponse
	(*TaskStatusRequest)(nil),        // 14: zeek_runner.TaskStatusRequest
	(*TaskStatusResponse)(nil),       // 15: zeek_runner.TaskStatusResponse
	(*ParentTaskStatusRequest)(nil),  // 16: zeek_runner.ParentTaskStatusRequest
	(*SubTaskSummary)(nil),           // 17: zeek_runner.SubTaskSummary
	(*ParentTaskStatusResponse)(nil), // 18: zeek_runner.ParentTaskStatusResponse
	(*ListScriptsRequest)(nil),       // 19: zeek_runner.ListScriptsRequest
	(*ScriptInfo)(nil),               // 20: zeek_runner.ScriptInfo
	(*ListScriptsResponse)(nil),      // 21: zeek_runner.ListScriptsResponse
	(*GetScriptRequest)(nil),         // 22: zeek_runner.GetScriptRequest
	(*ReloadScriptsRequest)(nil),     // 23: zeek_runner.ReloadScriptsRequest
	(*ReloadScriptsResponse)(nil),    // 24: zeek_runner.ReloadScriptsResponse
}
var file_api_pb_zeek_runner_proto_depIdxs = []int32{
	17, // 0: zeek_runner.ParentTaskStatusResponse.subTasks:type_name -> zeek_runner.SubTaskSummary
	20, // 1: zeek_runner.ListScriptsResponse.scripts:type_name -> zeek_runner.ScriptInfo
	20, // 2: zeek_runner.ReloadScriptsResponse.scripts:type_name -> zeek_runner.ScriptInfo
	0,  // 3: zeek_runner.ZeekAnalysisService.Analyze:input_type -> zeek_runner.AnalyzeRequest
	10, // 4: zeek_runner.ZeekAnalysisService.AsyncAnalyze:input_type -> zeek_runner.AsyncAnalyzeRequest
	2,  // 5: zeek_runner.ZeekAnalysisService.Extract:input_type -> zeek_runner.ExtractRequest
	12, // 6: zeek_runner.ZeekAnalysisService.ExtractAsync:input_type -> zeek_runner.ExtractAsyncRequest
	14, // 7: zeek_runner.ZeekAnalysisService.GetTaskStatus:input_type -> zeek_runner.TaskStatusRequest
	16, // 8: zeek_runner.ZeekAnalysisService.GetParentTaskStatus:input_type -> zeek_runner.ParentTaskStatusRequest
	4,  // 9: zeek_runner.ZeekAnalysisService.HealthCheck:input_type -> zeek_runner.HealthCheckRequest
	6,  // 10: zeek_runner.ZeekAnalysisService.VersionCheck:input_type -> zeek_runner.VersionCheckRequest
	8,  // 11: zeek_runner.ZeekAnalysisService.ZeekSyntaxCheck:input_type -> zeek_runner.ZeekSyntaxCheckRequest
	19, // 12: zeek_runner.ZeekAnalysisService.ListScripts:input_type -> zeek_runner.ListScriptsRequest
	22, // 13: zeek_runner.ZeekAnalysisService.GetScript:input_type -> zeek_runner.GetScriptRequest
	23, // 14: zeek_runner.ZeekAnalysisService.ReloadScripts:input_type -> zeek_runner.ReloadScriptsRequest
	1,  // 15: zeek_runner.ZeekAnalysisService.Analyze:output_type -> zeek_runner.AnalyzeResponse
	11, // 16: zeek_runner.ZeekAnalysisService.AsyncAnalyze:output_type -> zeek_runner.AsyncAnalyzeResponse
	3,  // 17: zeek_runner.ZeekAnalysisService.Extract:output_type -> zeek_runner.ExtractResponse
	13, // 18: zeek_runner.ZeekAnalysisService.ExtractAsync:output_type -> zeek_runner.ExtractAsyncResponse
	15, // 19: zeek_runner.ZeekAnalysisService.GetTaskStatus:output_type -> zeek_runner.TaskStatusResponse
	18, // 20: zeek_runner.ZeekAnalysisService.GetParentTaskStatus:output_type -> zeek_runner.ParentTaskStatusResponse
	5,  // 21: zeek_runner.ZeekAnalysisService.HealthCheck:output_type -> zeek_runner.HealthCheckResponse
	7,  // 22: zeek_runner.ZeekAnalysisService.VersionCheck:output_type -> zeek_runner.VersionCheckResponse
	9,  // 23: zeek_runner.ZeekAnalysisService.ZeekSyntaxCheck:output_type -> zeek_runner.ZeekSyntaxCheckResponse
	21, // 24: zeek_runner.ZeekAnalysisService.ListScripts:output_type -> zeek_runner.ListScriptsResponse
	20, // 25: zeek_runner.ZeekAnalysisService.GetScript:output_type -> zeek_runner.ScriptInfo
	24, // 26: zeek_runner.ZeekAnalysisService.ReloadScripts:output_type -> zeek_runner.ReloadScriptsResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_pb_zeek_runner_proto_init() }
func file_api_pb_zeek_runner_proto_init() {
	if File_api_pb_zeek_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_zeek_runner_proto_rawDesc), len(file_api_pb_zeek_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_zeek_runner_proto_goTypes,
		DependencyIndexes: file_api_pb_zeek_runner_proto_depIdxs,
		MessageInfos:      file_api_pb_zeek_runner_proto_msgTypes,
	}.Build()
	File_api_pb_zeek_runner_proto = out.File
	file_api_pb_zeek_runner_proto_goTypes = nil
	file_api_pb_zeek_runner_proto_depIdxs = nil
}
